(function(){
'use strict';
const E=window.ElevattaERP,V=window.ElevattaValidator,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const T=['apontamentos','fvs','fvsItens','medicoes','fotos','pacotes','funcionarios','config','frentes','ferramentas','termosFerramentas','movimentosFerramentas','importacoes','importOcorrencias','auditoria','obras','equipes','usuarios'];
let PAGE='dashboard',DATA={},FRONT_META=new Map(),loading=false,validationReports=[],toolTab='inventory',signature=null;
const titles={dashboard:'Visão geral',apontamentos:'Apontamentos',qualidade:'Qualidade / FVS',validacao:'Validação & Consolidação',ferramentas:'Ferramentas / Almoxarifado',cadastros:'Cadastros',administracao:'Administração'};
const fmtDate=x=>{if(!x)return'—';const s=String(x).slice(0,10),p=s.split('-');return p.length===3?p[2]+'/'+p[1]+'/'+p[0]:x};
const fmtDT=x=>{if(!x)return'—';try{return new Date(x).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}catch{return x}};
const n=x=>Number(x)||0,pct=x=>(100*n(x)).toLocaleString('pt-BR',{maximumFractionDigits:1})+'%',num=x=>n(x).toLocaleString('pt-BR',{maximumFractionDigits:2});
const norm=x=>E.upper(x),today=()=>new Date().toISOString().slice(0,10);
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),2600)}
function tag(t,cls=''){return '<span class="tag '+cls+'">'+esc(t||'—')+'</span>'}
function imageSrc(u){u=String(u||'').trim();if(!u)return'';if(u.startsWith('/api/erp/file?'))return u;if(/^https:\/\//i.test(u)&&/(sharepoint\.com|1drv\.ms)/i.test(u))return '/api/erp/file?url='+encodeURIComponent(u);return u}
function statusClass(s){s=norm(s);return /(APROV|CONFORM|DISPONIVEL|FECHADO|SINCRONIZ)/.test(s)?'ok':/(NAO CONFORM|AVARI|EXTRAVI|REJEIT|BLOQUE|CRIT)/.test(s)?'bad':/(PEND|USO|ALERTA|MANUT)/.test(s)?'warn':'blue'}
function filters(){return {de:$('fDe').value,ate:$('fAte').value,obra:$('fObra').value,pac:$('fPacote').value,pav:$('fPav').value,local:$('fLocal').value,func:$('fFunc').value}}
function frontMeta(r){const fid=r?.FRENTE_ID||E.frontId({obra:r?.OBRA,pacote:r?.PACOTE_COD,pavimento:r?.PAVIMENTO,local:r?.LOCAL_FRENTE||r?.LOCAL});return FRONT_META.get(fid)||r||{}}
function passCommon(r,f){const d=String(r.DATA||r.DATA_HORA||r.DATA_HORA_SAIDA||'').slice(0,10),fm=frontMeta(r),obra=r.OBRA||fm.OBRA||'',pac=r.PACOTE_COD||fm.PACOTE_COD||'',pav=r.PAVIMENTO||fm.PAVIMENTO||'',local=r.LOCAL_FRENTE||r.LOCAL||fm.LOCAL_FRENTE||fm.LOCAL||'';if(f.de&&d&&d<f.de)return false;if(f.ate&&d&&d>f.ate)return false;if(f.obra&&String(obra)!==f.obra)return false;if(f.pac&&String(pac)!==f.pac)return false;if(f.pav&&String(pav)!==f.pav)return false;if(f.local&&String(local)!==f.local)return false;if(f.func){const direct=String(r.MATRICULA||r.FUNCIONARIO_ID||'');if(direct&&direct!==f.func)return false;if(!direct){const fid=r.FRENTE_ID||fm.FRENTE_ID||'';if(!fid||!(DATA.apontamentos||[]).some(a=>frontOf(a)===fid&&String(a.MATRICULA||a.FUNCIONARIO_ID||'')===f.func))return false}}return true}
function rows(k,filtered=true){const a=DATA[k]||[];return filtered?a.filter(r=>passCommon(r,filters())):a}
function toolStatus(t){return norm(t.STATUS||'CADASTRO PENDENTE')}
function frontOf(r){return r.FRENTE_ID||E.frontId({obra:r.OBRA,pacote:r.PACOTE_COD,pavimento:r.PAVIMENTO,local:r.LOCAL_FRENTE||r.LOCAL})}
function currentPackage(c){return (DATA.pacotes||[]).find(p=>String(p.CODIGO)===String(c))||{}}
function getLatestBy(list,keyFn,dateFn=x=>x.DATA||x.UPDATED_AT){const m=new Map();for(const x of list){const k=keyFn(x),old=m.get(k);if(!old||String(dateFn(x)||'')>String(dateFn(old)||''))m.set(k,x)}return m}
function setPage(p){PAGE=p;document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('on',b.dataset.page===p));$('pageTitle').textContent=titles[p]||p;$('eyebrow').textContent='ELEVATTA · '+(p==='dashboard'?'CONTROL TOWER':'ERP INTEGRADO');location.hash=p==='dashboard'?'':p;render();if(innerWidth<821)$('sidebar').classList.remove('show')}
function drawer(title,body,ey='DETALHE'){ $('drawerTitle').textContent=title;$('drawerEyebrow').textContent=ey;$('drawerBody').innerHTML=body;$('drawer').classList.add('show');$('drawerBackdrop').classList.add('show') }
function closeDrawer(){$('drawer').classList.remove('show');$('drawerBackdrop').classList.remove('show');signature=null}

async function loadData(force=false){if(loading)return;loading=true;try{const s=await E.snapshot(T,{timeout:60000});DATA=s.tables||{};normalizeData();buildFilters();render();await updateStatus();if(s.stale&&s.error)toast('Base offline carregada · '+s.error)}catch(e){$('content').innerHTML='<div class="empty"><b>Não foi possível abrir a base.</b><br>'+esc(e.message)+'</div>'}finally{loading=false}}
function normalizeData(){for(const k of T)DATA[k]=Array.isArray(DATA[k])?DATA[k]:[];FRONT_META=new Map();const merge=x=>{const fid=x?.FRENTE_ID||E.frontId({obra:x?.OBRA,pacote:x?.PACOTE_COD,pavimento:x?.PAVIMENTO,local:x?.LOCAL_FRENTE||x?.LOCAL});if(!fid)return;const old=FRONT_META.get(fid)||{FRENTE_ID:fid};FRONT_META.set(fid,{...old,...Object.fromEntries(Object.entries(x||{}).filter(([,v])=>v!==''&&v!=null)),FRENTE_ID:fid})};(DATA.frentes||[]).forEach(merge);[...(DATA.apontamentos||[]),...(DATA.fvs||[]),...(DATA.medicoes||[]),...(DATA.movimentosFerramentas||[])].forEach(merge)}
function buildFilters(){const vals=(arr,field)=>[...new Set(arr.map(x=>String(x[field]||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'pt-BR'));
 const ap=DATA.apontamentos||[],f=filters(); const setSel=(id,label,list,value)=>{const e=$(id);e.innerHTML='<option value="">'+label+'</option>'+list.map(x=>'<option'+(x===value?' selected':'')+'>'+esc(x)+'</option>').join('')};
 setSel('fObra','Todas',vals([...ap,...DATA.fvs,...DATA.movimentosFerramentas],'OBRA'),f.obra);setSel('fPacote','Todos',vals([...ap,...DATA.fvs,...DATA.movimentosFerramentas],'PACOTE_COD'),f.pac);setSel('fPav','Todos',vals([...ap,...DATA.fvs,...DATA.movimentosFerramentas],'PAVIMENTO'),f.pav);setSel('fLocal','Todos',vals([...ap,...DATA.fvs,...DATA.movimentosFerramentas].map(x=>({...x,LOCAL_FRENTE:x.LOCAL_FRENTE||x.LOCAL})),'LOCAL_FRENTE'),f.local);
 const fun=DATA.funcionarios||[];$('fFunc').innerHTML='<option value="">Todos</option>'+fun.map(x=>'<option value="'+esc(x.MATRICULA||x.FUNCIONARIO_ID)+'"'+((x.MATRICULA||x.FUNCIONARIO_ID)===f.func?' selected':'')+'>'+esc((x.MATRICULA||'')+' · '+(x.NOME||''))+'</option>').join('');
 const dates=ap.map(x=>String(x.DATA||'')).filter(Boolean).sort();if(!$('fDe').value&&dates.length)$('fDe').value=dates[0];if(!$('fAte').value&&dates.length)$('fAte').value=dates[dates.length-1];if(!$('fDe').value){const d=new Date();d.setDate(1);$('fDe').value=d.toISOString().slice(0,10);$('fAte').value=today()}}
async function updateStatus(){await E.pendingCount().catch(()=>{});let txt;if(!navigator.onLine)txt='Offline · '+E.state.pending+' pendência(s) protegida(s)';else if(E.state.busy)txt='Sincronizando '+E.state.pending+' pendência(s)…';else if(E.state.blocked)txt='Online · '+E.state.blocked+' conflito(s) para revisar';else if(E.state.lastError)txt='Online · pendência protegida';else txt=E.state.pending?E.state.pending+' pendência(s)':'Online · sincronizado';$('netText').textContent=txt;$('netDot').className='net-dot '+(!navigator.onLine?'off':(!E.state.pending&&!E.state.lastError?'ok':''))}

function groupId(r){const fid=frontOf(r);if(fid)return fid;const k=E.frontKey(r||{});return 'SEM-FRENTE-'+E.hash12(k||[r?.ID,r?.DATA,r?.MATRICULA].join('|')).toUpperCase()}
function consolidate(){const ap=rows('apontamentos').filter(x=>!x.MOTIVO_FALTA&&n(x.FRACAO_DIA)>0),seedFvs=rows('fvs'),seedMov=rows('movimentosFerramentas'),selected=new Set([...ap,...seedFvs,...seedMov].map(frontOf).filter(Boolean)),fvs=(DATA.fvs||[]).filter(x=>selected.has(frontOf(x))),med=(DATA.medicoes||[]).filter(x=>selected.has(frontOf(x))),photos=(DATA.fotos||[]).filter(x=>selected.has(frontOf(x))),mov=(DATA.movimentosFerramentas||[]).filter(x=>selected.has(frontOf(x)));const G=new Map();function g(id,seed={}){id=id||groupId(seed);const real=frontOf(seed),meta=(real&&FRONT_META.get(real))||seed;if(!G.has(id))G.set(id,{id,unresolved:!real,obra:meta.OBRA||seed.OBRA||'',pac:meta.PACOTE_COD||seed.PACOTE_COD||'',serv:meta.PACOTE_SERVICO||seed.PACOTE_SERVICO||'',etapa:meta.ETAPA||seed.ETAPA||'',pav:meta.PAVIMENTO||seed.PAVIMENTO||'',local:meta.LOCAL_FRENTE||meta.LOCAL||seed.LOCAL_FRENTE||seed.LOCAL||'',dh:0,pessoas:new Set(),ap:[],fvs:[],med:[],photos:[],mov:[]});return G.get(id)}
 ap.forEach(x=>{const a=g(groupId(x),x);a.ap.push(x);a.dh+=n(x.FRACAO_DIA);if(x.MATRICULA)a.pessoas.add(x.MATRICULA);Object.assign(a,{obra:a.obra||x.OBRA,pac:a.pac||x.PACOTE_COD,serv:a.serv||x.PACOTE_SERVICO,etapa:a.etapa||x.ETAPA,pav:a.pav||x.PAVIMENTO,local:a.local||x.LOCAL_FRENTE})});
 seedFvs.forEach(x=>g(groupId(x),x));seedMov.forEach(x=>g(groupId(x),x));fvs.forEach(x=>g(groupId(x),x).fvs.push(x));med.forEach(x=>g(groupId(x),x).med.push(x));photos.forEach(x=>g(groupId(x),x).photos.push(x));mov.forEach(x=>g(groupId(x),x).mov.push(x));
 return [...G.values()].filter(x=>x.ap.length||x.fvs.length||x.mov.length).sort((a,b)=>b.dh-a.dh)}
function fvsState(g){if(!g.fvs.length)return {label:'NÃO',cls:'bad',rec:null};const rec=[...g.fvs].sort((a,b)=>String(b.DATA||b.UPDATED_AT).localeCompare(String(a.DATA||a.UPDATED_AT)))[0],s=norm(rec.SITUACAO);if(s==='APROVADA'||(n(rec.NAO_CONFORMES)===0&&n(rec.PENDENTES)===0&&n(rec.CONFORMES)>0))return {label:'SIM',cls:'ok',rec};return {label:s.includes('NAO CONFORM')?'NC / NÃO':'PENDÊNCIA',cls:s.includes('NAO CONFORM')?'bad':'warn',rec}}
function toolsOpen(mov){const last=new Map();[...mov].sort((a,b)=>String(a.DATA_HORA).localeCompare(String(b.DATA_HORA))).forEach(x=>last.set(String(x.FERRAMENTA_ID),x));return [...last.values()].filter(x=>norm(x.TIPO)==='SAIDA')}
function photoThumbs(arr){const p=arr.filter(x=>x.ARQUIVO_URL).slice(0,3);return p.length?'<div class="photos">'+p.map(x=>'<img loading="lazy" src="'+esc(imageSrc(x.ARQUIVO_URL))+'" alt="">').join('')+(arr.length>3?'<em>+'+(arr.length-3)+'</em>':'')+'</div>':'<span class="muted">—</span>'}

function renderDashboard(){const G=consolidate(),ap=rows('apontamentos').filter(x=>!x.MOTIVO_FALTA&&n(x.FRACAO_DIA)>0),fvs=rows('fvs'),mov=rows('movimentosFerramentas'),dh=ap.reduce((a,x)=>a+n(x.FRACAO_DIA),0),people=new Set(ap.map(x=>x.MATRICULA).filter(Boolean)).size,qual=G.filter(x=>!x.unresolved&&fvsState(x).label==='SIM').length,nc=fvs.filter(x=>n(x.NAO_CONFORMES)>0||norm(x.SITUACAO).includes('NAO CONFORM')).length,openTools=toolsOpen(mov).length,resolved=G.filter(x=>!x.unresolved).length,coverage=resolved?Math.round(100*qual/resolved):0;
 let h='<div class="hero"><div><small>ERP OPERACIONAL INTEGRADO</small><h2>Produção, qualidade e recursos na mesma frente.</h2><p>Os indicadores abaixo usam os filtros globais e vinculam apontamentos, FVS, fotos, medições e ferramentas pela FRENTE_ID.</p></div><div class="hero-actions"><a href="/?modo=ap">Novo apontamento</a><a href="/?modo=rf">Nova FVS</a><button onclick="ERP.goto(\'ferramentas\')">Movimentar ferramenta</button></div></div>';
 h+='<div class="kpis">'+kpi('Dias-homem',num(dh),people+' pessoas','var(--navy)')+kpi('Frentes',G.length,(G.filter(x=>x.unresolved).length?G.filter(x=>x.unresolved).length+' sem localização':'todas identificadas'),'var(--blue)')+kpi('Conferidas',coverage+'%',qual+' com FVS aprovada','var(--green)')+kpi('NC / pendências',nc,'FVS com restrição',nc?'var(--red)':'var(--green)')+kpi('Ferramentas em uso',openTools,'no recorte','var(--amber)')+kpi('Fila offline',E.state.pending,'aguardando sync',E.state.pending?'var(--orange)':'var(--green)')+'</div>';
 h+='<div class="panel"><div class="panel-head"><div><h3>Consolidação por frente de serviço</h3><p>Clique em uma linha para consultar a FVS, imagens, medição, pessoas e ferramentas sem sair desta página.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Frente</th><th>Obra</th><th>Pacote</th><th>Local</th><th>DH</th><th>Pessoas</th><th>Conferido</th><th>FVS</th><th>Fotos</th><th>Ferramentas</th></tr></thead><tbody>';
 h+=G.length?G.map(g=>{const q=fvsState(g),open=toolsOpen(g.mov);return '<tr onclick="ERP.openFront(\''+esc(g.id)+'\')"><td><b>'+esc(g.unresolved?'LOCALIZAÇÃO PENDENTE':g.id)+'</b></td><td>'+esc(g.obra||'—')+'</td><td><b>'+esc(g.pac||'—')+'</b><br><span class="muted">'+esc(g.serv||'')+'</span></td><td>'+esc([g.pav,g.local].filter(Boolean).join(' · ')||'—')+'</td><td>'+num(g.dh)+'</td><td>'+g.pessoas.size+'</td><td>'+tag(q.label,q.cls)+'</td><td>'+(q.rec?esc(q.rec.ID):'—')+'</td><td>'+photoThumbs(g.photos)+'</td><td>'+tag(String(open.length)+' em uso',open.length?'warn':'ok')+'</td></tr>'}).join(''):'<tr><td colspan="10"><div class="empty">Nenhuma frente encontrada neste recorte.</div></td></tr>';
 h+='</tbody></table></div></div>';return h}
function kpi(t,v,s,c){return '<div class="kpi" style="--c:'+c+'"><span>'+esc(t)+'</span><b>'+esc(v)+'</b><small>'+esc(s)+'</small></div>'}

function renderAp(){const L=rows('apontamentos');let h='<div class="hero"><div><small>MÓDULO 01</small><h2>Apontamentos</h2><p>Consulta central do esforço diário. O lançamento operacional continua disponível no PWA mobile e sincroniza automaticamente.</p></div><div class="hero-actions"><a href="/?modo=ap">Abrir lançamento operacional</a></div></div>';
 h+='<div class="kpis">'+kpi('Lançamentos',L.length,'linhas','var(--blue)')+kpi('Dias-homem',num(L.reduce((a,x)=>a+n(x.FRACAO_DIA),0)),'esforço','var(--navy)')+kpi('Pessoas',new Set(L.map(x=>x.MATRICULA)).size,'no período','var(--green)')+kpi('Retrabalho',num(L.filter(x=>norm(x.CLASSIFICACAO).includes('RETRAB')).reduce((a,x)=>a+n(x.FRACAO_DIA),0)),'dh','var(--red)')+kpi('Impedimento',num(L.filter(x=>norm(x.CLASSIFICACAO).includes('IMPED')).reduce((a,x)=>a+n(x.FRACAO_DIA),0)),'dh','var(--amber)')+kpi('Frentes',new Set(L.map(frontOf).filter(Boolean)).size,'vínculos identificados','var(--orange)')+'</div>';
 h+='<div class="panel"><div class="panel-head"><div><h3>Detalhamento</h3><p>Dados normalizados na base SharePoint.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Funcionário</th><th>Obra</th><th>Pacote</th><th>Pav./Local</th><th>Equipe</th><th>Fração</th><th>Classificação</th><th>Situação</th></tr></thead><tbody>'+L.map(x=>'<tr onclick="ERP.openFront(\''+esc(groupId(x))+'\')"><td>'+fmtDate(x.DATA)+'</td><td><b>'+esc(x.NOME||x.MATRICULA)+'</b><br><span class="muted">'+esc(x.MATRICULA)+'</span></td><td>'+esc(x.OBRA)+'</td><td><b>'+esc(x.PACOTE_COD)+'</b><br>'+esc(x.PACOTE_SERVICO)+'</td><td>'+esc([x.PAVIMENTO,x.LOCAL_FRENTE].filter(Boolean).join(' · ')||'—')+'</td><td>'+esc(x.EQUIPE||'—')+'</td><td>'+num(x.FRACAO_DIA)+'</td><td>'+tag(x.CLASSIFICACAO,statusClass(x.CLASSIFICACAO))+'</td><td>'+tag(x.SITUACAO,statusClass(x.SITUACAO))+'</td></tr>').join('')+'</tbody></table></div></div>';return h}

function renderQuality(){const L=rows('fvs');let h='<div class="hero"><div><small>MÓDULO 02</small><h2>Qualidade / FVS + Medição</h2><p>FVS, evidências fotográficas, não conformidades e avanço físico ligados à mesma frente de produção.</p></div><div class="hero-actions"><a href="/?modo=rf">Abrir FVS operacional</a></div></div>';
 const appr=L.filter(x=>fvsState({fvs:[x]}).label==='SIM').length,nc=L.filter(x=>n(x.NAO_CONFORMES)>0).length,ph=rows('fotos').length,med=rows('medicoes');h+='<div class="kpis">'+kpi('FVS',L.length,'registros','var(--blue)')+kpi('Aprovadas',appr,'serviços conferidos','var(--green)')+kpi('Com NC',nc,'exigem tratamento','var(--red)')+kpi('Fotos',ph,'evidências','var(--orange)')+kpi('Medições',med.length,'registros físicos','var(--navy)')+kpi('Medido médio',med.length?pct(med.reduce((a,x)=>a+n(x.ACUMULADO_PCT),0)/med.length):'0%','acumulado','var(--green)')+'</div>';
 h+='<div class="panel"><div class="panel-head"><div><h3>Fichas registradas</h3><p>Abra uma ficha para consultar o relatório e as imagens dentro do ERP.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Obra</th><th>Pacote</th><th>Local</th><th>Tipo</th><th>Situação</th><th>C</th><th>NC</th><th>Fotos</th></tr></thead><tbody>'+L.map(x=>'<tr onclick="ERP.openFvs(\''+esc(x.ID)+'\')"><td>'+fmtDate(x.DATA)+'</td><td>'+esc(x.OBRA)+'</td><td><b>'+esc(x.PACOTE_COD)+'</b><br>'+esc(x.PACOTE_SERVICO)+'</td><td>'+esc(x.LOCAL||'—')+'</td><td>'+tag(x.TIPO,'blue')+'</td><td>'+tag(x.SITUACAO,statusClass(x.SITUACAO))+'</td><td>'+n(x.CONFORMES)+'</td><td>'+n(x.NAO_CONFORMES)+'</td><td>'+n(x.QTD_FOTOS)+'</td></tr>').join('')+'</tbody></table></div></div>';return h}

function renderValidator(){let h='<div class="hero"><div><small>MÓDULO 03</small><h2>Validação & Consolidação</h2><p>O arquivo é analisado pelo conteúdo, não pelo nome da aba. Linhas inválidas entram em quarentena e somente dados aprovados podem ser enviados à base central.</p></div><div class="hero-actions"><button onclick="ERP.openLegacyValidator()">Abrir consolidador REV38 legado</button></div></div>';
 h+='<div class="panel"><div class="dropzone" id="valDrop"><b>Solte os arquivos de apontamento aqui</b><span>.xlsx ou .csv · pode selecionar vários dias</span><input id="valFiles" type="file" accept=".xlsx,.csv" multiple hidden></div><div id="valResults"></div></div>';
 const I=(DATA.importacoes||[]).sort((a,b)=>String(b.UPDATED_AT).localeCompare(String(a.UPDATED_AT))).slice(0,40);h+='<div class="panel"><div class="panel-head"><div><h3>Histórico de importações</h3><p>Hash do arquivo impede incorporar o mesmo export duas vezes.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Arquivo</th><th>Período</th><th>Status</th><th>Aceitas</th><th>Quarentena</th><th>Alertas</th></tr></thead><tbody>'+I.map(x=>'<tr><td><b>'+esc(x.ARQUIVO_NOME)+'</b><br><span class="muted">'+esc(String(x.ARQUIVO_HASH||'').slice(0,16))+'…</span></td><td>'+fmtDate(x.DATA_INICIO)+' → '+fmtDate(x.DATA_FIM)+'</td><td>'+tag(x.STATUS,statusClass(x.STATUS))+'</td><td>'+n(x.LINHAS_ACEITAS)+'</td><td>'+n(x.LINHAS_QUARENTENA)+'</td><td>'+n(x.ALERTAS)+'</td></tr>').join('')+'</tbody></table></div></div>';return h}
function bindValidator(){const drop=$('valDrop'),inp=$('valFiles');if(!drop||!inp)return;drop.onclick=()=>inp.click();inp.onchange=()=>processFiles([...inp.files]);['dragenter','dragover'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.add('drag')}));['dragleave','drop'].forEach(ev=>drop.addEventListener(ev,e=>{e.preventDefault();drop.classList.remove('drag')}));drop.addEventListener('drop',e=>processFiles([...e.dataTransfer.files]))}
function employeeAliases(){const out=[];for(const r of (DATA.config||[])){if(!String(r.CHAVE||'').startsWith('ALIAS_FUNC-'))continue;try{const a=JSON.parse(String(r.VALOR||'{}'));if(a.sourceMat&&a.sourceName&&a.targetMat)out.push(a)}catch{}}return out}
function validationCatalog(){return {funcionarios:DATA.funcionarios||[],pacotes:DATA.pacotes||[],aliases:employeeAliases()}}
async function processFiles(files){if(!files.length)return;const out=$('valResults');out.innerHTML='<div class="loading-card">Validando '+files.length+' arquivo(s)…</div>';validationReports=[];const seenDate=new Map();for(const file of files){try{const rep=await V.parseFile(file,validationCatalog());rep._file=file;for(const d of new Set(rep.apontamentos.map(x=>x.DATA))){if(seenDate.has(d)){rep.ocorrencias.push({SEVERIDADE:'ALERTA',TIPO:'DIA_DUPLICADO_NO_LOTE',DATA:d,ARQUIVO:file.name,DETALHE:'Outro arquivo selecionado também contém '+fmtDate(d)+'.',ACAO:'Confirme qual arquivo representa o dia correto.'});rep.importacao.ALERTAS++;rep.importacao.STATUS='APROVADO_COM_ALERTAS'}else seenDate.set(d,file.name)}validationReports.push(rep)}catch(e){validationReports.push({_file:file,error:e.message,importacao:{ARQUIVO_NOME:file.name,STATUS:'REJEITADO',LINHAS_ACEITAS:0,LINHAS_QUARENTENA:0,CRITICOS:1,ALERTAS:0},ocorrencias:[]})}}renderValidationResults()}
function groupedIssues(issues){
 const map=new Map();for(const x of (issues||[])){const groupable=['FUNCIONARIO_NAO_CADASTRADO','LOCAL_AUSENTE','COLUNA_OPCIONAL_AUSENTE','PACOTE_NAO_CADASTRADO','PACOTE_SEM_CODIGO','PACOTE_DEPARA_NECESSARIO'].includes(x.TIPO),k=groupable?[x.SEVERIDADE,x.TIPO,x.CAMPO||'',x.VALOR||'',x.DETALHE||'',x.ACAO||''].join('|'):'ROW|'+(x.OCORRENCIA_ID||Math.random());const g=map.get(k)||{...x,_count:0,_dates:new Set(),_lines:[]};g._count++;if(x.DATA)g._dates.add(x.DATA);if(x.LINHA&&g._lines.length<5)g._lines.push(x.LINHA);map.set(k,g)}return [...map.values()].sort((a,b)=>{const p=x=>x.SEVERIDADE==='CRITICO'?0:x.SEVERIDADE==='ALERTA'?1:2;return p(a)-p(b)||b._count-a._count})}
function renderValidationResults(){const out=$('valResults');if(!out)return;out.innerHTML=validationReports.map((r,i)=>{const m=r.importacao||{},issues=r.ocorrencias||[],display=groupedIssues(issues),cls=statusClass(m.STATUS);return '<div class="panel" style="margin-top:12px"><div class="panel-head"><div><h3>'+esc(m.ARQUIVO_NOME||r._file?.name)+'</h3><p>'+esc(r.error||('Hash '+String(m.ARQUIVO_HASH||'').slice(0,18)+'…'))+'</p></div>'+tag(m.STATUS,cls)+'</div><div class="validation-summary"><div><span>Aceitas</span><b>'+n(m.LINHAS_ACEITAS)+'</b></div><div><span>Quarentena</span><b>'+n(m.LINHAS_QUARENTENA)+'</b></div><div><span>Críticos</span><b>'+n(m.CRITICOS)+'</b></div><div><span>Alertas</span><b>'+n(m.ALERTAS)+'</b></div><div><span>Grupos a revisar</span><b>'+display.length+'</b></div><div><span>Período</span><b style="font-size:11px">'+fmtDate(m.DATA_INICIO)+'<br>'+fmtDate(m.DATA_FIM)+'</b></div></div>'+(display.length?'<div>'+display.slice(0,60).map(x=>{const dates=[...(x._dates||[])].sort(),where=x._count>1?(x._count+' ocorrências'+(dates.length?(' · '+dates.map(fmtDate).slice(0,3).join(', ')+(dates.length>3?'…':'')):'')+(x._lines?.length?(' · linhas '+x._lines.join(', ')):'') ):((x.DATA?fmtDate(x.DATA):'')+(x.LINHA?' · linha '+x.LINHA:''));const mapBtn=x.TIPO==='FUNCIONARIO_NAO_CADASTRADO'?'<div class="button-row compact"><button class="btn" onclick="ERP.mapEmployee('+i+','+JSON.stringify(String(x.VALOR||''))+','+JSON.stringify(String(x.NOME_ORIGEM||''))+')">Definir de/para</button></div>':'';return '<div class="issue"><div class="sev '+(x.SEVERIDADE==='CRITICO'?'crit':x.SEVERIDADE==='ALERTA'?'warn':'info')+'">'+esc(x.SEVERIDADE)+'</div><div><b>'+esc(x.TIPO)+'</b><p>'+esc(where)+'</p></div><div><b>'+esc(x.DETALHE||'')+'</b><p>'+esc(x.ACAO||'')+'</p>'+mapBtn+'</div></div>'}).join('')+'</div>':'<div class="empty">Nenhuma ocorrência relevante.</div>')+(!['REJEITADO','BLOQUEADO'].includes(m.STATUS)?'<div class="button-row"><button class="btn green" onclick="ERP.commitValidation('+i+')">Gravar no ERP / SharePoint</button></div>':'<div class="empty" style="margin-top:10px"><b>Importação bloqueada.</b> Corrija os itens críticos e valide o arquivo novamente.</div>')+'</div>'}).join('')}
function mapEmployee(i,oldMat,oldName){const funcs=(DATA.funcionarios||[]).filter(x=>norm(x.ATIVO||'SIM')!=='NAO');drawer('De/para de colaborador','<div class="form-card"><p><b>Origem histórica:</b><br>'+esc(oldMat)+' · '+esc(oldName||'nome não informado')+'</p><label>Vincular ao funcionário atual<select id="aliasTarget">'+options(funcs.map(x=>({value:x.MATRICULA,label:(x.MATRICULA||'')+' · '+x.NOME})),'','Selecione…')+'</select></label><div class="button-row"><button class="btn green" onclick="ERP.saveEmployeeAlias('+i+','+JSON.stringify(String(oldMat||''))+','+JSON.stringify(String(oldName||''))+')">Salvar de/para e revalidar</button></div><p class="muted" style="font-size:10px">A associação vale apenas para esta combinação de matrícula + nome histórico. Matrículas antigas com nomes diferentes continuam separadas para evitar vínculo incorreto.</p></div>','MIGRAÇÃO CONTROLADA')}
async function saveEmployeeAlias(i,oldMat,oldName){try{const target=$('aliasTarget')?.value;if(!target)throw new Error('Selecione o funcionário atual.');const alias={sourceMat:String(oldMat||''),sourceName:String(oldName||''),targetMat:String(target)},row={CHAVE:'ALIAS_FUNC-'+E.hash12(E.upper(oldMat)+'|'+E.upper(oldName)).toUpperCase(),VALOR:JSON.stringify(alias),DESCRICAO:(oldMat+' · '+oldName)+' → '+target,UPDATED_AT:new Date().toISOString()};await E.queue({key:'CONFIG-'+row.CHAVE,type:'GENERIC',payload:{operations:[{table:'config',rows:[row]}],audit:{action:'DEPARA_FUNCIONARIO',entityType:'CONFIG',entityId:row.CHAVE,after:alias,user:'',deviceId:E.deviceId()}},assets:[]});const idx=(DATA.config||[]).findIndex(x=>String(x.CHAVE)===row.CHAVE);if(idx>=0)DATA.config[idx]=row;else(DATA.config||(DATA.config=[])).push(row);await E.cacheTable('config',DATA.config);const current=validationReports[i];if(current?._file){const rep=await V.parseFile(current._file,validationCatalog());rep._file=current._file;validationReports[i]=rep}closeDrawer();renderValidationResults();toast('De/para salvo no aparelho e aplicado à validação.')}catch(e){toast(e.message)}}
async function commitValidation(i){const r=validationReports[i];if(!r)return;try{await E.commitImport(r,r._file);toast('Importação protegida no aparelho · sincronização automática');await loadData(false)}catch(e){toast(e.message)}}

function renderTools(){const tools=DATA.ferramentas||[],available=tools.filter(t=>toolStatus(t)==='DISPONIVEL').length,inuse=tools.filter(t=>toolStatus(t)==='EM USO').length,maint=tools.filter(t=>/MANUT|AVARI/.test(toolStatus(t))).length,open=openTerms().length;let h='<div class="hero"><div><small>MÓDULO 04</small><h2>Ferramentas / Almoxarifado</h2><p>Cada ativo tem número próprio. A saída registra funcionário, obra, pacote/frente, assinatura e condição; a devolução fecha o histórico sem apagar movimentações.</p></div></div>';
 h+='<div class="kpis">'+kpi('Cadastradas',tools.filter(t=>norm(t.ATIVO)==='SIM').length,'de '+tools.length+' posições','var(--navy)')+kpi('Disponíveis',available,'para retirada','var(--green)')+kpi('Em uso',inuse,'fora do almoxarifado','var(--amber)')+kpi('Manutenção/avaria',maint,'bloqueadas','var(--red)')+kpi('Termos abertos',open,'aguardando devolução','var(--blue)')+kpi('Fila offline',E.state.pending,'todas as operações','var(--orange)')+'</div>';
 h+='<div class="tabs"><button class="'+(toolTab==='inventory'?'on':'')+'" onclick="ERP.toolTab(\'inventory\')">Inventário</button><button class="'+(toolTab==='checkout'?'on':'')+'" onclick="ERP.toolTab(\'checkout\')">Registrar saída</button><button class="'+(toolTab==='return'?'on':'')+'" onclick="ERP.toolTab(\'return\')">Registrar devolução</button><button class="'+(toolTab==='history'?'on':'')+'" onclick="ERP.toolTab(\'history\')">Histórico</button></div>';
 if(toolTab==='inventory')h+=toolInventory();else if(toolTab==='checkout')h+=toolCheckoutForm();else if(toolTab==='return')h+=toolReturnForm();else h+=toolHistory();return h}
function toolInventory(){const L=(DATA.ferramentas||[]).slice().sort((a,b)=>n(a.NUMERO)-n(b.NUMERO));return '<div class="panel"><div class="panel-head"><div><h3>Patrimônio 001–050</h3><p>Itens ainda não cadastrados ficam bloqueados para retirada.</p></div></div><div class="tool-grid">'+L.map(t=>'<div class="tool-card" onclick="ERP.editTool(\''+esc(t.FERRAMENTA_ID)+'\')"><div class="tool-img">'+(t.FOTO_PRINCIPAL_URL||t.FOTO_REFERENCIA_URL?'<img loading="lazy" src="'+esc(imageSrc(t.FOTO_PRINCIPAL_URL||t.FOTO_REFERENCIA_URL))+'" alt="">':'IMAGEM PENDENTE')+'</div><div class="tool-copy"><span class="num">FER-'+String(n(t.NUMERO)).padStart(3,'0')+'</span><b>'+esc(t.NOME||'A cadastrar')+'</b><small>'+tag(t.STATUS,statusClass(t.STATUS))+' '+esc([t.MARCA,t.MODELO].filter(Boolean).join(' · '))+'</small></div></div>').join('')+'</div></div>'}
function options(arr,val,lab){return '<option value="">'+lab+'</option>'+arr.map(x=>'<option value="'+esc(x.value)+'"'+(String(x.value)===String(val)?' selected':'')+'>'+esc(x.label)+'</option>').join('')}
function toolCheckoutForm(){const funcs=(DATA.funcionarios||[]).filter(x=>norm(x.ATIVO||'SIM')!=='NAO'),packs=(DATA.pacotes||[]).filter(x=>!/(INATIV|ARQUIV)/.test(norm(x.STATUS))),works=[...new Set([...(DATA.obras||[]).filter(x=>norm(x.ATIVO||'SIM')!=='NAO').map(x=>x.NOME||x.OBRA),...DATA.apontamentos.map(x=>x.OBRA),...DATA.fvs.map(x=>x.OBRA)].filter(Boolean))].sort(),tools=(DATA.ferramentas||[]).filter(t=>toolStatus(t)==='DISPONIVEL'&&norm(t.ATIVO||'SIM')!=='NAO');return '<div class="form-card"><div class="panel-head"><div><h3>Novo termo de retirada</h3><p>A assinatura é salva primeiro no aparelho. Se a internet cair, o termo permanece pendente e sincroniza sozinho depois.</p></div></div><div class="form-grid"><label>Funcionário<select id="toEmp">'+options(funcs.map(x=>({value:x.MATRICULA,label:(x.MATRICULA||'')+' · '+x.NOME})),'','Selecione…')+'</select></label><label>Obra<select id="toObra">'+options(works.map(x=>({value:x,label:x})),'','Selecione…')+'</select></label><label>Pacote<select id="toPack">'+options(packs.map(x=>({value:x.CODIGO,label:x.CODIGO+' · '+x.PACOTE_SERVICO})),'','Selecione…')+'</select></label><label>Pavimento<input id="toPav" placeholder="Ex.: Térreo"></label><label class="wide">Local / frente<input id="toLocal" placeholder="Ex.: AP 101 · banheiro suíte"></label><label>Almoxarife<input id="toAlm" placeholder="Quem entregou"></label><label class="full">Observação<textarea id="toObs" placeholder="Opcional"></textarea></label></div><div class="panel-head" style="margin-top:14px"><div><h3>Ferramentas disponíveis</h3><p>'+tools.length+' disponíveis neste aparelho.</p></div></div><div class="check-grid">'+tools.map(t=>'<label class="check-item"><input type="checkbox" name="toolOut" value="'+esc(t.FERRAMENTA_ID)+'"><span><b>'+String(n(t.NUMERO)).padStart(3,'0')+' · '+esc(t.NOME)+'</b><small>'+esc(t.CONDICAO_ATUAL||'Condição não informada')+'</small></span></label>').join('')+'</div><div style="margin-top:14px"><b style="font-size:11px">Assinatura de quem retirou</b><div class="signature" id="signBox"><canvas id="signCanvas"></canvas><div class="signature-foot"><span>Assine com o dedo ou mouse</span><button class="btn" type="button" onclick="ERP.clearSignature()">Limpar</button></div></div></div><div class="button-row"><button class="btn green" onclick="ERP.checkoutTools()">Confirmar retirada</button></div></div>'}
function openTerms(){const terms=(DATA.termosFerramentas||[]).filter(t=>norm(t.STATUS)!=='FECHADO'),mov=DATA.movimentosFerramentas||[];return terms.map(t=>{const last=new Map();mov.filter(m=>String(m.TERMO_ID)===String(t.TERMO_ID)).sort((a,b)=>String(a.DATA_HORA).localeCompare(String(b.DATA_HORA))).forEach(m=>last.set(String(m.FERRAMENTA_ID),m));const open=[...last.values()].filter(x=>norm(x.TIPO)==='SAIDA');return {term:t,open}}).filter(x=>x.open.length)}
function toolReturnForm(){const ots=openTerms();if(!ots.length)return '<div class="empty">Nenhum termo aberto com ferramenta pendente de devolução.</div>';return '<div class="form-card"><div class="panel-head"><div><h3>Devolução</h3><p>Escolha um termo aberto. Cada ferramenta pode receber condição e foto da devolução.</p></div></div><label style="font:700 8px ui-monospace,monospace;color:#71849a">TERMO<select id="trTerm" onchange="ERP.renderReturnTerm()" style="display:block;width:100%;margin-top:5px;height:40px;border:1px solid var(--line);border-radius:9px">'+options(ots.map(x=>({value:x.term.TERMO_ID,label:fmtDT(x.term.DATA_HORA_SAIDA)+' · '+x.term.FUNCIONARIO_NOME+' · '+x.open.length+' item(ns)'})),'','Selecione…')+'</select></label><div id="returnTermBody" style="margin-top:12px"></div></div>'}
function renderReturnTerm(){const id=$('trTerm')?.value,ot=openTerms().find(x=>String(x.term.TERMO_ID)===String(id)),box=$('returnTermBody');if(!box)return;if(!ot){box.innerHTML='';return}box.innerHTML='<div class="detail-grid"><div><span>Funcionário</span><b>'+esc(ot.term.FUNCIONARIO_NOME)+'</b></div><div><span>Obra</span><b>'+esc(ot.term.OBRA)+'</b></div><div><span>Pacote</span><b>'+esc(ot.term.PACOTE_COD)+'</b></div></div><div style="margin-top:12px">'+ot.open.map(m=>'<div class="form-card" style="padding:11px"><label class="check-item"><input type="checkbox" name="toolReturn" value="'+esc(m.FERRAMENTA_ID)+'" checked><span><b>'+String(n(m.NUMERO)).padStart(3,'0')+' · '+esc(m.FERRAMENTA_NOME)+'</b><small>Retirada '+fmtDT(m.DATA_HORA)+'</small></span></label><div class="form-grid" style="margin-top:8px"><label>Condição<select id="cond_'+esc(m.FERRAMENTA_ID)+'"><option>OK</option><option>AVARIADA</option><option>MANUTENCAO</option><option>INCOMPLETA</option></select></label><label class="wide">Foto da devolução<input type="file" accept="image/*" id="photo_'+esc(m.FERRAMENTA_ID)+'"></label></div></div>').join('')+'</div><div class="form-grid"><label>Recebido por<input id="trReceiver" placeholder="Almoxarife"></label><label class="wide">Observação<input id="trObs" placeholder="Opcional"></label></div><div class="button-row"><button class="btn green" onclick="ERP.returnTools()">Confirmar devolução</button></div>'}
function toolHistory(){const M=rows('movimentosFerramentas').slice().sort((a,b)=>String(b.DATA_HORA).localeCompare(String(a.DATA_HORA)));return '<div class="panel"><div class="panel-head"><div><h3>Livro razão de ferramentas</h3><p>O histórico respeita os filtros globais. Abra o termo para consultar assinatura, saída, devolução e evidências.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data/hora</th><th>Ferramenta</th><th>Movimento</th><th>Funcionário</th><th>Obra / pacote</th><th>Condição</th><th>Termo</th></tr></thead><tbody>'+M.map(x=>'<tr><td>'+fmtDT(x.DATA_HORA)+'</td><td><b>'+String(n(x.NUMERO)).padStart(3,'0')+' · '+esc(x.FERRAMENTA_NOME)+'</b></td><td>'+tag(x.TIPO,norm(x.TIPO)==='DEVOLUCAO'?'ok':'warn')+'</td><td>'+esc(x.FUNCIONARIO_NOME||'—')+'</td><td>'+esc(x.OBRA||'')+'<br><span class="muted">'+esc(x.PACOTE_COD||'')+'</span></td><td>'+tag(x.CONDICAO,statusClass(x.CONDICAO))+'</td><td><button class="link-btn" onclick="ERP.openToolTerm('+JSON.stringify(String(x.TERMO_ID||''))+')">'+esc(x.TERMO_ID||'—')+'</button></td></tr>').join('')+'</tbody></table></div></div>'}
function toolTermDetail(id){const t=(DATA.termosFerramentas||[]).find(x=>String(x.TERMO_ID)===String(id));if(!t)return '<div class="empty">Termo não localizado.</div>';const M=(DATA.movimentosFerramentas||[]).filter(x=>String(x.TERMO_ID)===String(id)).slice().sort((a,b)=>String(a.DATA_HORA).localeCompare(String(b.DATA_HORA))),last=new Map();M.forEach(x=>last.set(String(x.FERRAMENTA_ID),x));const pend=[...last.values()].filter(x=>norm(x.TIPO)==='SAIDA').length,sig=t.ASSINATURA_URL?'<figure class="signature-proof"><img src="'+esc(imageSrc(t.ASSINATURA_URL))+'" alt="Assinatura do responsável pela retirada"><figcaption>Assinatura registrada na retirada · hash '+esc(String(t.ASSINATURA_HASH||'').slice(0,16))+'…</figcaption></figure>':(t.ASSINATURA_HASH?'<div class="empty"><b>Assinatura protegida no aparelho.</b><br>O arquivo ficará disponível aqui após a sincronização com o SharePoint.</div>':'<div class="empty">Assinatura não localizada neste termo.</div>');return '<div class="detail-grid"><div><span>Termo</span><b>'+esc(t.TERMO_ID)+'</b></div><div><span>Status operacional</span><b>'+tag(pend?'ABERTO':'FECHADO',pend?'warn':'ok')+'</b></div><div><span>Saída</span><b>'+fmtDT(t.DATA_HORA_SAIDA)+'</b></div><div><span>Funcionário</span><b>'+esc((t.MATRICULA? t.MATRICULA+' · ':'')+(t.FUNCIONARIO_NOME||'—'))+'</b></div><div><span>Obra</span><b>'+esc(t.OBRA||'—')+'</b></div><div><span>Pacote / frente</span><b>'+esc((t.PACOTE_COD||'—')+' · '+(t.LOCAL_FRENTE||'—'))+'</b></div><div><span>Almoxarife</span><b>'+esc(t.RESPONSAVEL_ALMOXARIFADO||'—')+'</b></div><div><span>Itens ainda em uso</span><b>'+pend+'</b></div></div><div class="panel"><div class="panel-head"><div><h3>Comprovante de retirada</h3><p>A assinatura é evidência operacional vinculada ao termo e ao funcionário.</p></div></div>'+sig+'</div><div class="panel"><div class="panel-head"><div><h3>Movimentações do termo</h3><p>'+M.length+' evento(s) preservado(s) no livro razão.</p></div></div>'+(M.length?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Quando</th><th>Ferramenta</th><th>Mov.</th><th>Condição</th><th>Recebido por</th><th>Evidência</th></tr></thead><tbody>'+M.map(x=>'<tr><td>'+fmtDT(x.DATA_HORA)+'</td><td><b>'+String(n(x.NUMERO)).padStart(3,'0')+' · '+esc(x.FERRAMENTA_NOME)+'</b></td><td>'+tag(x.TIPO,norm(x.TIPO)==='DEVOLUCAO'?'ok':'warn')+'</td><td>'+tag(x.CONDICAO,statusClass(x.CONDICAO))+'</td><td>'+esc(x.RECEBIDO_POR||'—')+'</td><td>'+(x.FOTO_URL?'<a class="link-btn" href="'+esc(imageSrc(x.FOTO_URL))+'" target="_blank" rel="noopener">Ver foto</a>':'—')+'</td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Sem movimentações.</div>')+'</div>'}
function openToolTerm(id){drawer('Termo '+id,toolTermDetail(id),'ALMOXARIFADO · RASTREABILIDADE')}

function renderCad(){const packs=DATA.pacotes||[],funcs=DATA.funcionarios||[],fronts=DATA.frentes||[];return '<div class="hero"><div><small>CADASTROS MESTRES</small><h2>Uma única fonte de verdade.</h2><p>Pacotes e funcionários continuam compartilhados por Apontamento, FVS, Medição e Ferramentas. Frentes são geradas automaticamente pelos lançamentos.</p></div></div><div class="grid2"><div class="panel"><div class="panel-head"><div><h3>Pacotes</h3><p>'+packs.length+' cadastrados</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Serviço</th><th>Etapa</th><th>Status</th></tr></thead><tbody>'+packs.map(x=>'<tr><td><b>'+esc(x.CODIGO)+'</b></td><td>'+esc(x.PACOTE_SERVICO)+'</td><td>'+esc(x.ETAPA)+'</td><td>'+tag(x.STATUS,statusClass(x.STATUS))+'</td></tr>').join('')+'</tbody></table></div></div><div><div class="panel"><div class="panel-head"><div><h3>Funcionários</h3><p>'+funcs.length+' cadastrados</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Matrícula</th><th>Nome</th><th>Função</th></tr></thead><tbody>'+funcs.map(x=>'<tr><td>'+esc(x.MATRICULA)+'</td><td><b>'+esc(x.NOME)+'</b></td><td>'+esc(x.FUNCAO)+'</td></tr>').join('')+'</tbody></table></div></div><div class="panel"><div class="panel-head"><div><h3>Frentes de serviço</h3><p>'+fronts.length+' identificadores persistentes</p></div></div><small class="muted">FRENTE_ID = obra + pacote + pavimento + local normalizados.</small></div></div></div>'}
async function renderAdmin(){
  const q=await E.db.all('outbox').catch(()=>[]),blocked=q.filter(x=>x.blocked),aud=(DATA.auditoria||[]).slice().sort((a,b)=>String(b.DATA_HORA).localeCompare(String(a.DATA_HORA))).slice(0,80);
  const qrows=q.map(x=>{
    const actions=x.blocked?'<div class="button-row compact"><button class="btn" onclick="ERP.retryTx('+JSON.stringify(String(x.key))+')">Tentar novamente</button><button class="btn danger" onclick="ERP.discardTx('+JSON.stringify(String(x.key))+')">Descartar pendência</button></div>':'';
    return '<tr><td><b>'+esc(x.type)+'</b><br><span class="muted">'+esc(x.key)+'</span></td><td>'+tag(x.blocked?'CONFLITO':'PENDENTE',x.blocked?'bad':'warn')+'</td><td>'+fmtDT(x.createdAt)+'</td><td>'+n(x.attempts)+'</td><td><span class="danger-text">'+esc(x.lastError||'—')+'</span>'+actions+'</td></tr>';
  }).join('');
  const arows=aud.map(x=>'<tr><td>'+fmtDT(x.DATA_HORA)+'</td><td>'+tag(x.ACAO,'blue')+'</td><td>'+esc(x.ENTIDADE_TIPO)+'<br><span class="muted">'+esc(x.ENTIDADE_ID)+'</span></td><td>'+esc(x.USUARIO||'—')+'</td></tr>').join('');
  return '<div class="hero"><div><small>ADMINISTRAÇÃO TÉCNICA</small><h2>Saúde da sincronização e auditoria.</h2><p>Nenhuma pendência offline é descartada em silêncio. Falhas transitórias tentam novamente; conflitos de negócio ficam bloqueados para revisão humana, sem repetir indefinidamente.</p></div><div class="hero-actions"><button onclick="location.href=\'/auth/login?returnTo=/erp.html#administracao\'">Entrar novamente no Microsoft 365</button></div></div>'+ 
    '<div class="kpis">'+kpi('Versão','40.1.0','ERP','var(--navy)')+kpi('Online',navigator.onLine?'SIM':'NÃO','navegador',navigator.onLine?'var(--green)':'var(--red)')+kpi('Pendências',q.length,'outbox','var(--orange)')+kpi('Conflitos',blocked.length,'revisão necessária',blocked.length?'var(--red)':'var(--green)')+kpi('Último sync',E.state.lastOkAt?new Date(E.state.lastOkAt).toLocaleTimeString('pt-BR'):'—','sessão atual','var(--blue)')+kpi('Armazenamento',E.state.storagePersistent?'PROTEGIDO':'PADRÃO',E.state.storageQuota?((E.state.storageUsage/1048576).toFixed(1)+' MB usados'):'IndexedDB','var(--navy)')+'</div>'+ 
    '<div class="grid2"><div class="panel"><div class="panel-head"><div><h3>Outbox offline</h3><p>Transações aguardando SharePoint. Conflitos não são descartados nem repetidos automaticamente.</p></div></div>'+(q.length?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Tipo</th><th>Estado</th><th>Criada</th><th>Tentativas</th><th>Erro / ação</th></tr></thead><tbody>'+qrows+'</tbody></table></div>':'<div class="empty">Fila vazia. Todos os registros locais foram enviados.</div>')+'</div>'+ 
    '<div class="panel"><div class="panel-head"><div><h3>Auditoria</h3><p>Últimos eventos no ERP.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Quando</th><th>Ação</th><th>Entidade</th><th>Usuário</th></tr></thead><tbody>'+arows+'</tbody></table></div></div></div>';
}

function render(){if(loading)return;let h;if(PAGE==='dashboard')h=renderDashboard();else if(PAGE==='apontamentos')h=renderAp();else if(PAGE==='qualidade')h=renderQuality();else if(PAGE==='validacao')h=renderValidator();else if(PAGE==='ferramentas')h=renderTools();else if(PAGE==='cadastros')h=renderCad();else{$('content').innerHTML='<div class="loading-card">Abrindo administração…</div>';renderAdmin().then(x=>$('content').innerHTML=x);return}$('content').innerHTML=h;if(PAGE==='validacao')bindValidator();if(PAGE==='ferramentas'&&toolTab==='checkout')setTimeout(initSignature,0);if(PAGE==='ferramentas'&&toolTab==='return')setTimeout(renderReturnTerm,0)}

function frontDetail(id){const g=consolidate().find(x=>String(x.id)===String(id));if(!g)return'<div class="empty">Frente não localizada no recorte atual.</div>';const q=fvsState(g),rec=q.rec,items=rec?(DATA.fvsItens||[]).filter(x=>String(x.REGISTRO_ID)===String(rec.ID)):[],photos=rec?(DATA.fotos||[]).filter(x=>String(x.REGISTRO_ID)===String(rec.ID)):g.photos,meds=g.med.slice().sort((a,b)=>String(b.DATA).localeCompare(String(a.DATA))),open=toolsOpen(g.mov);let h=(g.unresolved?'<div class="panel" style="border-left:4px solid var(--amber)"><b>Frente não identificada automaticamente</b><p class="muted">Este apontamento não possui pavimento/local suficiente. Ele permanece na produção, mas não é vinculado automaticamente a FVS, medição ou ferramentas para evitar associação incorreta.</p></div>':'')+'<div class="detail-grid"><div><span>Obra</span><b>'+esc(g.obra||'—')+'</b></div><div><span>Pacote</span><b>'+esc(g.pac+' · '+(g.serv||''))+'</b></div><div><span>Local</span><b>'+esc([g.pav,g.local].filter(Boolean).join(' · ')||'—')+'</b></div><div><span>Dias-homem</span><b>'+num(g.dh)+'</b></div><div><span>Pessoas</span><b>'+g.pessoas.size+'</b></div><div><span>Conferido</span><b>'+tag(q.label,q.cls)+'</b></div></div>';
 h+='<div class="panel"><div class="panel-head"><div><h3>Qualidade</h3><p>'+(rec?'FVS '+esc(rec.ID):'Nenhuma FVS vinculada')+'</p></div></div>'+(rec?'<div class="detail-grid"><div><span>Data</span><b>'+fmtDate(rec.DATA)+'</b></div><div><span>Responsável</span><b>'+esc(rec.RESPONSAVEL||'—')+'</b></div><div><span>Situação</span><b>'+tag(rec.SITUACAO,statusClass(rec.SITUACAO))+'</b></div><div><span>Conformes</span><b>'+n(rec.CONFORMES)+'</b></div><div><span>Não conformes</span><b>'+n(rec.NAO_CONFORMES)+'</b></div><div><span>Pendentes</span><b>'+n(rec.PENDENTES)+'</b></div></div>'+(items.length?'<div class="table-wrap" style="margin-top:10px"><table class="data-table"><thead><tr><th>Item</th><th>Verificação</th><th>Critério</th><th>Status</th><th>Obs.</th></tr></thead><tbody>'+items.map(x=>'<tr><td>'+n(x.ITEM)+'</td><td><b>'+esc(x.VERIFICACAO)+'</b></td><td>'+esc(x.CRITERIO)+'</td><td>'+tag(x.STATUS,statusClass(x.STATUS))+'</td><td>'+esc(x.OBSERVACAO||'—')+'</td></tr>').join('')+'</tbody></table></div>':''):'<div class="empty">Serviço ainda não conferido por FVS.</div>')+'</div>';
 h+='<div class="panel"><div class="panel-head"><div><h3>Evidências fotográficas</h3><p>'+photos.length+' foto(s) vinculada(s)</p></div></div>'+(photos.length?'<div class="photo-gallery">'+photos.map(x=>'<figure><a href="'+esc(imageSrc(x.ARQUIVO_URL))+'" target="_blank" rel="noopener"><img loading="lazy" src="'+esc(imageSrc(x.ARQUIVO_URL))+'" alt="Foto FVS"></a><figcaption>'+esc(x.ITEM?('Item '+x.ITEM+' · '):'')+esc(x.LEGENDA||x.ARQUIVO_NOME||'Evidência')+'</figcaption></figure>').join('')+'</div>':'<div class="empty">Sem fotografia sincronizada.</div>')+'</div>';
 h+='<div class="split"><div class="panel"><div class="panel-head"><div><h3>Medição física</h3></div></div>'+(meds.length?meds.map(x=>'<div class="detail-grid"><div><span>Executado</span><b>'+pct(x.EXECUTADO_PCT)+'</b></div><div><span>Aprovado FVS</span><b>'+pct(x.APROVADO_PCT)+'</b></div><div><span>Acumulado</span><b>'+pct(x.ACUMULADO_PCT)+'</b></div></div>').join(''):'<div class="empty">Sem medição vinculada.</div>')+'</div><div class="panel"><div class="panel-head"><div><h3>Ferramentas</h3><p>'+open.length+' ainda em uso</p></div></div>'+(g.mov.length?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Ferramenta</th><th>Mov.</th><th>Quando</th><th>Funcionário</th><th>Termo</th></tr></thead><tbody>'+g.mov.slice().sort((a,b)=>String(b.DATA_HORA).localeCompare(String(a.DATA_HORA))).map(x=>'<tr><td><b>'+String(n(x.NUMERO)).padStart(3,'0')+' · '+esc(x.FERRAMENTA_NOME)+'</b></td><td>'+tag(x.TIPO,norm(x.TIPO)==='DEVOLUCAO'?'ok':'warn')+'</td><td>'+fmtDT(x.DATA_HORA)+'</td><td>'+esc(x.FUNCIONARIO_NOME||'—')+'</td><td><button class="link-btn" onclick="ERP.openToolTerm('+JSON.stringify(String(x.TERMO_ID||''))+')">'+esc(x.TERMO_ID||'—')+'</button></td></tr>').join('')+'</tbody></table></div>':'<div class="empty">Nenhuma ferramenta vinculada à frente.</div>')+'</div></div>';return h}
function openFront(id){drawer('Frente '+id,frontDetail(id),'CONSOLIDAÇÃO INTEGRADA')}
function openFvs(id){const x=(DATA.fvs||[]).find(a=>String(a.ID)===String(id));if(!x)return;const fid=frontOf(x);if(fid)return openFront(fid);drawer('FVS '+id,'<div class="empty">Registro sem FRENTE_ID.</div>')}

function toolTabSet(t){toolTab=t;render()}
function editTool(id){const t=(DATA.ferramentas||[]).find(x=>String(x.FERRAMENTA_ID)===String(id));if(!t)return;const q=encodeURIComponent([t.NOME,t.MARCA,t.MODELO].filter(Boolean).join(' '));drawer(String(n(t.NUMERO)).padStart(3,'0')+' · '+(t.NOME||'A cadastrar'),'<div class="form-card"><div class="form-grid"><label>Número<input value="'+esc(t.NUMERO)+'" disabled></label><label class="wide">Nome<input id="edName" value="'+esc(t.NOME||'')+'" placeholder="Ex.: Martelete"></label><label>Categoria<input id="edCat" value="'+esc(t.CATEGORIA||'')+'"></label><label>Marca<input id="edBrand" value="'+esc(t.MARCA||'')+'"></label><label>Modelo<input id="edModel" value="'+esc(t.MODELO||'')+'"></label><label>Nº série<input id="edSerial" value="'+esc(t.NUMERO_SERIE||'')+'"></label><label>Status<select id="edStatus"><option>DISPONIVEL</option><option>EM USO</option><option>MANUTENCAO</option><option>AVARIADA</option><option>EXTRAVIADA</option><option>BAIXADA</option><option>CADASTRO PENDENTE</option></select></label><label>Condição<input id="edCond" value="'+esc(t.CONDICAO_ATUAL||'')+'"></label><label>Ativo<select id="edActive"><option>SIM</option><option>NAO</option></select></label><label class="wide">Foto real<input id="edPhoto" type="file" accept="image/*"></label><label class="full">URL imagem de referência<input id="edRef" value="'+esc(t.FOTO_REFERENCIA_URL||'')+'" placeholder="Cole a URL da imagem de referência"></label><label class="full">Origem da referência<input id="edRefOrigin" value="'+esc(t.FOTO_REFERENCIA_ORIGEM||'')+'" placeholder="URL da página/fabricante"></label><label class="full">Observação<textarea id="edObs">'+esc(t.OBSERVACAO||'')+'</textarea></label></div><div class="button-row"><a class="btn" target="_blank" rel="noopener" href="https://www.google.com/search?tbm=isch&q='+q+'">Pesquisar imagem de referência</a><button class="btn green" onclick="ERP.saveTool(\''+esc(id)+'\')">Salvar ferramenta</button></div><p class="muted" style="font-size:9px">Uma imagem da internet é tratada como referência. A foto real do patrimônio, quando cadastrada, tem prioridade.</p></div>','CADASTRO DE FERRAMENTA');setTimeout(()=>{$('edStatus').value=t.STATUS||'CADASTRO PENDENTE';$('edActive').value=t.ATIVO||'NAO'},0)}
async function saveTool(id){const t=(DATA.ferramentas||[]).find(x=>String(x.FERRAMENTA_ID)===String(id));if(!t)return;const row={...t,NOME:$('edName').value,CATEGORIA:$('edCat').value,MARCA:$('edBrand').value,MODELO:$('edModel').value,NUMERO_SERIE:$('edSerial').value,STATUS:$('edStatus').value,CONDICAO_ATUAL:$('edCond').value,ATIVO:$('edActive').value,FOTO_REFERENCIA_URL:$('edRef').value,FOTO_REFERENCIA_ORIGEM:$('edRefOrigin').value,OBSERVACAO:$('edObs').value,UPDATED_AT:new Date().toISOString()},payload={operations:[{table:'ferramentas',rows:[row]}],audit:{action:'ATUALIZAR_FERRAMENTA',entityType:'FERRAMENTA',entityId:id,after:row,user:'',deviceId:E.deviceId()}},assets=[];const f=$('edPhoto').files?.[0];if(f){const key=await E.saveAsset(f,{name:id+'.jpg',folder:'Ferramentas/Catalogo'});assets.push({assetKey:key,folder:'Ferramentas/Catalogo',name:id+'.jpg',target:'operations.0.rows.0.FOTO_PRINCIPAL_URL'})}await E.queue({key:'TOOL-MASTER-'+id,type:'GENERIC',payload,assets});Object.assign(t,row);await E.cacheTable('ferramentas',DATA.ferramentas);closeDrawer();toast('Ferramenta salva no aparelho');render()}
function initSignature(){const c=$('signCanvas');if(!c)return;const rect=c.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1);c.width=Math.round(rect.width*dpr);c.height=Math.round(170*dpr);const ctx=c.getContext('2d');ctx.scale(dpr,dpr);ctx.lineWidth=2.2;ctx.lineCap='round';ctx.strokeStyle='#112b49';let down=false,empty=true;const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?.[0]||e;return{x:p.clientX-r.left,y:p.clientY-r.top}};const start=e=>{e.preventDefault();down=true;const p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y)};const move=e=>{if(!down)return;e.preventDefault();const p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();empty=false};const end=()=>{down=false};c.onpointerdown=start;c.onpointermove=move;c.onpointerup=end;c.onpointercancel=end;signature={canvas:c,ctx,isEmpty:()=>empty,clear:()=>{ctx.clearRect(0,0,rect.width,170);empty=true}}}
function clearSignature(){signature?.clear()}
async function canvasBlob(c){return new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(new Error('Falha ao gerar assinatura.')),'image/png'))}
async function checkoutTools(){try{const mat=$('toEmp').value,emp=(DATA.funcionarios||[]).find(x=>String(x.MATRICULA)===String(mat)),obra=$('toObra').value,code=$('toPack').value,pack=currentPackage(code),ids=[...document.querySelectorAll('input[name=toolOut]:checked')].map(x=>x.value),tools=ids.map(id=>(DATA.ferramentas||[]).find(t=>String(t.FERRAMENTA_ID)===id)).filter(Boolean);if(!emp)throw new Error('Selecione o funcionário.');if(!obra)throw new Error('Selecione a obra.');if(!pack.CODIGO)throw new Error('Selecione o pacote.');if(!norm($('toLocal').value))throw new Error('Informe o local / frente de uso.');if(!norm($('toAlm').value))throw new Error('Informe quem entregou no almoxarifado.');if(!tools.length)throw new Error('Selecione pelo menos uma ferramenta.');if(!signature||signature.isEmpty())throw new Error('A assinatura de quem retirou é obrigatória.');const sig=await canvasBlob(signature.canvas),r=await E.toolCheckout({employee:{id:E.employeeId(emp.MATRICULA),matricula:emp.MATRICULA,nome:emp.NOME},obra,pacote:{codigo:pack.CODIGO,nome:pack.PACOTE_SERVICO,etapa:pack.ETAPA},pavimento:$('toPav').value,local:$('toLocal').value,almoxarife:$('toAlm').value,observacao:$('toObs').value,tools,signatureBlob:sig});DATA.termosFerramentas.push(r.term);DATA.movimentosFerramentas.push(...(r.movements||[]));for(const t of tools)t.STATUS='EM USO';await Promise.all([E.cacheTable('ferramentas',DATA.ferramentas),E.cacheTable('termosFerramentas',DATA.termosFerramentas),E.cacheTable('movimentosFerramentas',DATA.movimentosFerramentas)]);toast('Retirada registrada offline ✓');toolTab='history';render();updateStatus()}catch(e){toast(e.message)}}
async function returnTools(){try{const id=$('trTerm').value,ot=openTerms().find(x=>String(x.term.TERMO_ID)===String(id));if(!ot)throw new Error('Selecione o termo.');const ids=[...document.querySelectorAll('input[name=toolReturn]:checked')].map(x=>x.value);if(!ids.length)throw new Error('Selecione ao menos uma ferramenta.');if(!norm($('trReceiver').value))throw new Error('Informe quem recebeu a devolução.');const items=[];for(const tid of ids){const base=(DATA.ferramentas||[]).find(x=>String(x.FERRAMENTA_ID)===String(tid))||ot.open.find(x=>String(x.FERRAMENTA_ID)===String(tid))||{};items.push({...base,returnCondition:document.getElementById('cond_'+tid)?.value||'OK',photoBlob:document.getElementById('photo_'+tid)?.files?.[0]||null})}const rr=await E.toolReturn({termId:id,items,employeeId:ot.term.FUNCIONARIO_ID,employeeName:ot.term.FUNCIONARIO_NOME,obraId:ot.term.OBRA_ID,obra:ot.term.OBRA,frenteId:ot.term.FRENTE_ID,pacoteCod:ot.term.PACOTE_COD,pacoteServico:ot.term.PACOTE_SERVICO,pavimento:ot.term.PAVIMENTO,local:ot.term.LOCAL_FRENTE,recebidoPor:$('trReceiver').value,observacao:$('trObs').value});DATA.movimentosFerramentas.push(...(rr.movements||[]));for(const t of items){const x=(DATA.ferramentas||[]).find(y=>String(y.FERRAMENTA_ID)===String(t.FERRAMENTA_ID));if(x)x.STATUS=/AVARI/.test(norm(t.returnCondition))?'AVARIADA':/MANUT/.test(norm(t.returnCondition))?'MANUTENCAO':'DISPONIVEL'}await Promise.all([E.cacheTable('ferramentas',DATA.ferramentas),E.cacheTable('movimentosFerramentas',DATA.movimentosFerramentas)]);toast('Devolução protegida no aparelho ✓');toolTab='history';render();updateStatus()}catch(e){toast(e.message)}}

async function retryTx(key){try{await E.retryTransaction(key);toast('Pendência liberada para nova tentativa.');await loadData(true)}catch(e){toast(e.message)}}
async function discardTx(key){if(!confirm('Descartar esta pendência local? Use apenas quando o conflito já estiver resolvido ou o lançamento não deva mais ser enviado.'))return;try{await E.discardTransaction(key);toast('Pendência descartada. Recarregando o estado central…');await loadData(true)}catch(e){toast(e.message)}}
function openLegacyValidator(){window.open('./consolidacao_rev38_legacy.html','_blank','noopener')}
function goto(p){setPage(p)}
async function syncNow(){try{const n=await E.flush({force:true});toast(n?n+' pendência(s) sincronizada(s)':'Nada pendente ou conexão indisponível');await loadData(true)}catch(e){toast(e.message)}finally{updateStatus()}}

const ERP={goto,openFront,openFvs,openToolTerm,toolTab:toolTabSet,editTool,saveTool,clearSignature,checkoutTools,returnTools,renderReturnTerm,commitValidation,mapEmployee,saveEmployeeAlias,openLegacyValidator,syncNow,retryTx,discardTx};window.ERP=ERP;

document.querySelectorAll('#sideNav button').forEach(b=>b.onclick=()=>setPage(b.dataset.page));$('drawerClose').onclick=closeDrawer;$('drawerBackdrop').onclick=closeDrawer;$('hamb').onclick=()=>$('sidebar').classList.toggle('show');$('openMobile').onclick=()=>location.href='/';$('syncBtn').onclick=syncNow;$('clearFilters').onclick=()=>{['fDe','fAte','fObra','fPacote','fPav','fLocal','fFunc'].forEach(id=>$(id).value='');buildFilters();render()};['fDe','fAte','fObra','fPacote','fPav','fLocal','fFunc'].forEach(id=>$(id).onchange=render);window.addEventListener('elevatta-erp-status',updateStatus);window.addEventListener('elevatta-erp-synced',()=>loadData(true));window.addEventListener('elevatta-erp-conflict',e=>{toast('Conflito de sincronização: '+(e.detail?.error||'revise a Administração'));loadData(true)});window.addEventListener('elevatta-erp-discarded',()=>loadData(true));window.addEventListener('online',()=>loadData(true));
const hash=location.hash.replace('#','');if(titles[hash])PAGE=hash;document.querySelectorAll('#sideNav button').forEach(b=>b.classList.toggle('on',b.dataset.page===PAGE));$('pageTitle').textContent=titles[PAGE];loadData();
})();
