import http from 'node:http';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';

const __filename=fileURLToPath(import.meta.url),root=path.dirname(__filename);
const port=Number(process.env.PORT||10000),host='0.0.0.0',VERSION='40.1.0';
const SCHEMA=JSON.parse(await fs.readFile(path.join(root,'erp-schema.json'),'utf8'));
const M365={tenant:String(process.env.M365_TENANT_ID||'organizations').trim()||'organizations',clientId:String(process.env.M365_CLIENT_ID||'').trim(),clientSecret:String(process.env.M365_CLIENT_SECRET||'').trim(),workbookUrl:String(process.env.M365_WORKBOOK_URL||'').trim(),sessionSecret:String(process.env.SESSION_SECRET||'').trim(),appBaseUrl:String(process.env.APP_BASE_URL||'').trim().replace(/\/+$/,'')};
const authConfigured=()=>Boolean(M365.clientId&&M365.clientSecret&&M365.sessionSecret),scope='openid profile offline_access User.Read Files.ReadWrite';
const SESSION_COOKIE='elevatta_m365_session',STATE_COOKIE='elevatta_m365_state',RETURN_COOKIE='elevatta_m365_return';
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.webmanifest':'application/manifest+json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.ico':'image/x-icon','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.md':'text/markdown; charset=utf-8','.txt':'text/plain; charset=utf-8'};

const base64url=b=>Buffer.from(b).toString('base64').replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
function unbase64url(s){const p=String(s||'').replace(/-/g,'+').replace(/_/g,'/');return Buffer.from(p+'='.repeat((4-(p.length%4))%4),'base64')}
function cryptoKey(){if(!M365.sessionSecret)throw new Error('SESSION_SECRET ausente');return crypto.createHash('sha256').update(M365.sessionSecret).digest()}
function seal(value){const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',cryptoKey(),iv),plain=Buffer.from(JSON.stringify(value),'utf8'),enc=Buffer.concat([cipher.update(plain),cipher.final()]),tag=cipher.getAuthTag();return [base64url(iv),base64url(enc),base64url(tag)].join('.')}
function unseal(token){try{const [a,b,c]=String(token||'').split('.');if(!a||!b||!c)return null;const d=crypto.createDecipheriv('aes-256-gcm',cryptoKey(),unbase64url(a));d.setAuthTag(unbase64url(c));return JSON.parse(Buffer.concat([d.update(unbase64url(b)),d.final()]).toString('utf8'))}catch{return null}}
function cookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i>0)out[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())});return out}
function cookie(name,value,opt={}){const p=[`${name}=${encodeURIComponent(value)}`,'Path=/'];if(opt.maxAge!=null)p.push(`Max-Age=${Math.max(0,Math.floor(opt.maxAge))}`);if(opt.httpOnly!==false)p.push('HttpOnly');p.push(`SameSite=${opt.sameSite||'Lax'}`);if(opt.secure!==false)p.push('Secure');return p.join('; ')}
const clearCookie=n=>cookie(n,'',{maxAge:0});
function requestOrigin(req){if(M365.appBaseUrl)return M365.appBaseUrl;const proto=String(req.headers['x-forwarded-proto']||'https').split(',')[0].trim()||'https',h=String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim();return `${proto}://${h}`.replace(/\/+$/,'')}
const safeReturnTo=v=>{const s=String(v||'/');return s.startsWith('/')&&!s.startsWith('//')?s:'/'};
function json(res,status,body,extra={}){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...extra});res.end(JSON.stringify(body))}
function redirect(res,location,extra={}){res.writeHead(302,{Location:location,'Cache-Control':'no-store',...extra});res.end()}
async function readJson(req,max=5*1024*1024){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)throw Object.assign(new Error('Payload muito grande.'),{status:413});chunks.push(c)}if(!chunks.length)return{};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Object.assign(new Error('JSON inválido.'),{status:400})}}
async function readRaw(req,max=20*1024*1024){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)throw Object.assign(new Error('Arquivo acima do limite de 20 MB.'),{status:413});chunks.push(c)}return Buffer.concat(chunks)}

async function tokenRequest(params){const r=await fetch(`https://login.microsoftonline.com/${encodeURIComponent(M365.tenant)}/oauth2/v2.0/token`,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(params)}),j=await r.json().catch(()=>({}));if(!r.ok){const e=new Error(j.error_description||j.error||`Microsoft token endpoint: ${r.status}`);e.status=r.status;e.code=j.error||'';throw e}return j}
const tokenCache=new Map();
function sessionCacheKey(raw){return crypto.createHash('sha256').update(String(raw||'')).digest('hex').slice(0,24)}
async function serverAccess(req){if(!authConfigured())throw Object.assign(new Error('Microsoft 365 não configurado no servidor.'),{status:503});const raw=cookies(req)[SESSION_COOKIE]||'',session=unseal(raw);if(!session?.refreshToken)throw Object.assign(new Error('Entre uma vez com sua conta Microsoft para ativar a sincronização.'),{status:401,reauthRequired:true});const k=sessionCacheKey(raw),hit=tokenCache.get(k);if(hit?.token&&hit.expiresAt>Date.now()+90000)return {token:hit.token};try{const t=await tokenRequest({client_id:M365.clientId,client_secret:M365.clientSecret,scope,refresh_token:session.refreshToken,grant_type:'refresh_token'}),expiresAt=Date.now()+Math.max(60,Number(t.expires_in)||3600)*1000;tokenCache.set(k,{token:t.access_token,expiresAt});let setCookie='';if(t.refresh_token&&t.refresh_token!==session.refreshToken){const sealed=seal({refreshToken:t.refresh_token,createdAt:session.createdAt||Date.now(),rotatedAt:Date.now()});setCookie=cookie(SESSION_COOKIE,sealed,{maxAge:90*24*60*60});tokenCache.set(sessionCacheKey(sealed),{token:t.access_token,expiresAt})}return {token:t.access_token,setCookie}}catch(e){tokenCache.delete(k);throw Object.assign(new Error('A sessão Microsoft expirou ou foi revogada. Entre novamente para retomar a sincronização.'),{status:401,reauthRequired:true,clearSession:true})}}

function retryDelay(r,attempt){const h=Number(r?.headers?.get?.('retry-after'));return Number.isFinite(h)&&h>0?Math.min(15000,h*1000):Math.min(6000,600*2**attempt)}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function graph(pathOrUrl,token,opt={}){const url=String(pathOrUrl).startsWith('http')?pathOrUrl:'https://graph.microsoft.com/v1.0'+pathOrUrl,headers={Authorization:'Bearer '+token,...(opt.headers||{})};if(opt.sessionId)headers['workbook-session-id']=opt.sessionId;let body;if(opt.body!==undefined){if(opt.raw)body=opt.body;else{headers['Content-Type']='application/json';body=JSON.stringify(opt.body)}}let r;for(let a=0;a<3;a++){r=await fetch(url,{method:opt.method||'GET',headers,body});if(![429,502,503,504].includes(r.status)||a===2)break;await sleep(retryDelay(r,a))}if(r.status===204)return null;const ct=r.headers.get('content-type')||'',j=ct.includes('json')?await r.json().catch(()=>({})):await r.arrayBuffer();if(!r.ok){const msg=j?.error?.message||j?.error_description||`Microsoft Graph: ${r.status}`,e=new Error(msg);e.status=r.status;e.code=j?.error?.code||'';throw e}return ct.includes('json')?j:Buffer.from(j)}
function encodeShareUrl(url){return 'u!'+base64url(Buffer.from(String(url),'utf8'))}
const locatorCache={url:'',data:null,at:0};
async function resolveWorkbook(token){if(!M365.workbookUrl)throw Object.assign(new Error('M365_WORKBOOK_URL não configurado no Render.'),{status:503});if(locatorCache.url===M365.workbookUrl&&locatorCache.data&&Date.now()-locatorCache.at<10*60*1000)return locatorCache.data;const x=await graph(`/shares/${encodeShareUrl(M365.workbookUrl)}/driveItem?$select=id,name,webUrl,parentReference`,token),l={driveId:x.parentReference?.driveId,itemId:x.id,parentId:x.parentReference?.id,name:x.name,webUrl:x.webUrl};if(!l.driveId||!l.itemId)throw new Error('Planilha do SharePoint não localizada.');locatorCache.url=M365.workbookUrl;locatorCache.data=l;locatorCache.at=Date.now();return l}
const tableDef=k=>{const d=SCHEMA.tables[k];if(!d)throw Object.assign(new Error('Tabela ERP não permitida: '+k),{status:400});return d};
const tablePath=(l,name,s='')=>`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(l.itemId)}/workbook/tables/${encodeURIComponent(name)}${s}`;
async function listRows(l,def,token,sessionId=''){let next=tablePath(l,def.name,'/rows?$top=1000'),out=[],pages=0;while(next&&pages<100){const j=await graph(next,token,{sessionId});out.push(...((j?.value||[]).map(r=>({index:r.index,values:(r.values&&r.values[0])||[]}))));next=j?.['@odata.nextLink']||'';pages++}return out}
function objRows(rows,headers){return rows.map(r=>{const o={__index:r.index};headers.forEach((h,i)=>o[h]=r.values[i]);return o}).filter(o=>String(o[headers[0]]??'').trim())}
function rowArray(obj,headers){return headers.map(h=>obj?.[h]??'')}
async function appendRows(l,def,rows,token,sessionId=''){const vals=(rows||[]).map(r=>Array.isArray(r)?r:rowArray(r,def.headers));for(let i=0;i<vals.length;i+=100)await graph(tablePath(l,def.name,'/rows'),token,{method:'POST',body:{values:vals.slice(i,i+100)},sessionId})}
async function updateRow(l,def,index,row,token,sessionId=''){await graph(tablePath(l,def.name,'/rows/'+index),token,{method:'PATCH',body:{values:[Array.isArray(row)?row:rowArray(row,def.headers)]},sessionId})}
async function deleteIndexes(l,def,indexes,token,sessionId=''){for(const i of [...indexes].sort((a,b)=>b-a))await graph(tablePath(l,def.name,'/rows/'+i),token,{method:'DELETE',sessionId})}
async function upsertObjects(l,key,objects,token,sessionId=''){const def=tableDef(key),existing=objRows(await listRows(l,def,token,sessionId),def.headers),pk=def.headers[0],by=new Map();existing.forEach(x=>{const id=String(x[pk]??'');if(id&&!by.has(id))by.set(id,x)});let added=0,updated=0;const inserts=[];for(const o of objects||[]){const id=String(o?.[pk]??'');if(!id)continue;const old=by.get(id);if(old){const merged={...old,...o};delete merged.__index;if(old.CRIADO_EM)merged.CRIADO_EM=old.CRIADO_EM;await updateRow(l,def,old.__index,merged,token,sessionId);by.set(id,{...merged,__index:old.__index});updated++}else{inserts.push(o);by.set(id,{...o,__index:-1});added++}}if(inserts.length)await appendRows(l,def,inserts,token,sessionId);return {added,updated}}
async function createSession(l,token){try{return (await graph(`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(l.itemId)}/workbook/createSession`,token,{method:'POST',body:{persistChanges:true}}))?.id||''}catch(e){console.warn('Excel createSession falhou; operação seguirá sem sessão:',e.message);return''}}
async function closeSession(l,token,sid){if(!sid)return;try{await graph(`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(l.itemId)}/workbook/closeSession`,token,{method:'POST',sessionId:sid})}catch{}}
async function withWorkbook(token,fn){const l=await resolveWorkbook(token),sid=await createSession(l,token);try{return await fn(l,sid)}finally{await closeSession(l,token,sid)}}

async function children(l,parentId,token){return (await graph(`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(parentId)}/children?$select=id,name,folder,webUrl&$top=200`,token))?.value||[]}
async function ensureFolder(l,parentId,name,token){const list=await children(l,parentId,token),found=list.find(x=>x.folder&&String(x.name).toLowerCase()===String(name).toLowerCase());if(found)return found;return graph(`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(parentId)}/children`,token,{method:'POST',body:{name,folder:{},'@microsoft.graph.conflictBehavior':'fail'}})}
async function ensureFolderPath(l,rel,token){let p=l.parentId;for(const seg of String(rel||'').split('/').map(s=>s.trim()).filter(Boolean)){const f=await ensureFolder(l,p,seg.replace(/["*:<>?/\\|]/g,'_').slice(0,90),token);p=f.id}return p}
async function uploadErpFile(l,folder,name,buf,contentType,token){const rootFolder=await ensureFolder(l,l.parentId,'ELEVATTA_ERP',token),parent=await ensureFolderPath({...l,parentId:rootFolder.id},folder,token),safe=String(name||'arquivo').replace(/["*:<>?/\\|]/g,'_').slice(0,180);return graph(`/drives/${encodeURIComponent(l.driveId)}/items/${encodeURIComponent(parent)}:/${encodeURIComponent(safe)}:/content`,token,{method:'PUT',body:buf,raw:true,headers:{'Content-Type':contentType||'application/octet-stream'}})}

let writeChain=Promise.resolve();
function serialized(fn){const run=writeChain.catch(()=>{}).then(fn);writeChain=run.catch(()=>{});return run}
const normStatus=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().trim();
const normKey=v=>String(v??'').trim().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ');
function fnv1a(str,seed=0x811c9dc5){let h=seed>>>0;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,0x01000193)>>>0}return h>>>0}
function hash12(str){const s=String(str);return fnv1a(s,0x811c9dc5).toString(16).padStart(8,'0')+fnv1a(s,0x9e3779b9).toString(16).padStart(8,'0').slice(0,4)}
function obraId(obra){const o=normKey(obra);return o?'OBR-'+hash12(o).toUpperCase():''}
function auditRow(action,type,id,before,after,user,device){const t=new Date().toISOString();return {AUDIT_ID:'AUD-'+crypto.randomUUID().replace(/-/g,'').slice(0,20).toUpperCase(),DATA_HORA:t,USUARIO:user||'',ACAO:action,ENTIDADE_TIPO:type,ENTIDADE_ID:id,ANTES_JSON:before?JSON.stringify(before).slice(0,15000):'',DEPOIS_JSON:after?JSON.stringify(after).slice(0,15000):'',DEVICE_ID:device||'',UPDATED_AT:t}}
function apSignature(o){return [o.DATA,o.MATRICULA,o.OBRA,o.PACOTE_COD,o.PAVIMENTO,o.LOCAL_FRENTE,Number(o.FRACAO_DIA||0).toFixed(4),o.CLASSIFICACAO,o.MOTIVO_FALTA].map(v=>String(v??'').trim().toUpperCase()).join('|')}

async function handleErp(req,res,url){
  if(url.pathname==='/api/erp/schema'&&req.method==='GET')return json(res,200,SCHEMA);
  let auth;try{auth=await serverAccess(req)}catch(e){const h={};if(e.clearSession)h['Set-Cookie']=clearCookie(SESSION_COOKIE);return json(res,e.status||401,{ok:false,reauthRequired:!!e.reauthRequired,error:e.message},h)}
  const extra=auth.setCookie?{'Set-Cookie':auth.setCookie}:{};const token=auth.token;
  try{
    if(url.pathname==='/api/erp/status'&&req.method==='GET'){const [l,me]=await Promise.all([resolveWorkbook(token),graph('/me?$select=displayName,mail,userPrincipalName',token)]);return json(res,200,{ok:true,version:VERSION,workbook:l.name,workbookUrl:l.webUrl,user:{name:me.displayName||'',email:me.mail||me.userPrincipalName||''}},extra)}
    if(url.pathname==='/api/erp/snapshot'&&req.method==='GET'){
      const keys=(url.searchParams.get('tables')||'').split(',').map(s=>s.trim()).filter(Boolean);if(!keys.length)throw Object.assign(new Error('Informe as tabelas do snapshot.'),{status:400});const l=await resolveWorkbook(token),out={};for(const k of keys){const def=tableDef(k);out[k]=objRows(await listRows(l,def,token),def.headers).map(x=>{delete x.__index;return x})}return json(res,200,{ok:true,version:VERSION,tables:out},extra)
    }
    if(url.pathname==='/api/erp/batch'&&req.method==='POST'){
      const body=await readJson(req);const result=await serialized(()=>withWorkbook(token,async(l,sid)=>{const r=[];for(const op of body.operations||[]){if(op.mode&&op.mode!=='upsert')throw Object.assign(new Error('Modo não suportado: '+op.mode),{status:400});r.push({table:op.table,...await upsertObjects(l,op.table,op.rows||[],token,sid)})}if(body.audit)await upsertObjects(l,'auditoria',[auditRow(body.audit.action||'BATCH',body.audit.entityType||'ERP',body.audit.entityId||'',null,body.audit.after||null,body.audit.user||'',body.audit.deviceId||'')],token,sid);return r}));return json(res,200,{ok:true,result},extra)
    }
    if(url.pathname==='/api/erp/file'&&req.method==='GET'){
      let itemId=String(url.searchParams.get('itemId')||''),name=String(url.searchParams.get('name')||''),driveId='';
      if(itemId){const l=await resolveWorkbook(token);driveId=l.driveId}
      else{const share=String(url.searchParams.get('url')||'');if(!/^https:\/\//i.test(share))throw Object.assign(new Error('Referência de arquivo inválida.'),{status:400});const it=await graph(`/shares/${encodeShareUrl(share)}/driveItem?$select=id,name,parentReference`,token);itemId=it.id||'';name=name||it.name||'';driveId=it.parentReference?.driveId||''}
      if(!itemId||!driveId)throw Object.assign(new Error('Arquivo não localizado.'),{status:404});const buf=await graph(`/drives/${encodeURIComponent(driveId)}/items/${encodeURIComponent(itemId)}/content`,token),ct=mime[path.extname(name).toLowerCase()]||'application/octet-stream';res.writeHead(200,{'Content-Type':ct,'Content-Length':buf.length,'Cache-Control':'private, max-age=300','X-Content-Type-Options':'nosniff',...extra});return res.end(buf)
    }
    if(url.pathname==='/api/erp/upload'&&req.method==='POST'){
      const buf=await readRaw(req),l=await resolveWorkbook(token),file=await uploadErpFile(l,url.searchParams.get('folder')||'',url.searchParams.get('name')||'arquivo',buf,req.headers['content-type'],token),appUrl='/api/erp/file?itemId='+encodeURIComponent(file.id)+'&name='+encodeURIComponent(file.name||'arquivo');return json(res,200,{ok:true,id:file.id,name:file.name,webUrl:file.webUrl,appUrl},extra)
    }
    if(url.pathname==='/api/erp/tools/checkout'&&req.method==='POST'){
      const b=await readJson(req);const result=await serialized(()=>withWorkbook(token,async(l,sid)=>{
        if(!b.term?.TERMO_ID||!(b.movements||[]).length)throw Object.assign(new Error('Retirada incompleta.'),{status:400});
        const ids=[...new Set((b.toolIds||[]).map(String).filter(Boolean))];if(ids.length!==(b.movements||[]).length)throw Object.assign(new Error('Há ferramenta repetida ou sem identificação na retirada.'),{status:400});
        const def=tableDef('ferramentas'),tools=objRows(await listRows(l,def,token,sid),def.headers),by=new Map(tools.map(x=>[String(x.FERRAMENTA_ID),x]));
        for(const id of ids){const t=by.get(String(id));if(!t)throw Object.assign(new Error('Ferramenta '+id+' não cadastrada.'),{status:409,details:{toolId:id}});const st=normStatus(t.STATUS);if(normStatus(t.ATIVO)!=='SIM')throw Object.assign(new Error(`Ferramenta ${t.NUMERO||id} está inativa.`),{status:409,details:{toolId:id,status:t.STATUS,active:t.ATIVO}});if(st!=='DISPONIVEL')throw Object.assign(new Error(`Ferramenta ${t.NUMERO||id} indisponível: ${t.STATUS||'status não informado'}.`),{status:409,details:{toolId:id,status:t.STATUS}})}
        await upsertObjects(l,'frentes',[b.front],token,sid);await upsertObjects(l,'termosFerramentas',[b.term],token,sid);await upsertObjects(l,'movimentosFerramentas',b.movements,token,sid);
        const updates=[];for(const id of ids){const old=by.get(String(id)),n={...old};delete n.__index;n.STATUS='EM USO';n.UPDATED_AT=new Date().toISOString();updates.push(n)}await upsertObjects(l,'ferramentas',updates,token,sid);
        await upsertObjects(l,'auditoria',[auditRow('RETIRADA','TERMO_FERRAMENTA',b.term.TERMO_ID,null,b.term,b.user,b.term.DEVICE_ID)],token,sid);return {termId:b.term.TERMO_ID,count:updates.length}
      }));return json(res,200,{ok:true,...result},extra)
    }
    if(url.pathname==='/api/erp/tools/return'&&req.method==='POST'){
      const b=await readJson(req);const result=await serialized(()=>withWorkbook(token,async(l,sid)=>{
        if(!b.termId||!(b.movements||[]).length)throw Object.assign(new Error('Devolução incompleta.'),{status:400});const td=tableDef('ferramentas'),tools=objRows(await listRows(l,td,token,sid),td.headers),by=new Map(tools.map(x=>[String(x.FERRAMENTA_ID),x]));
        const termDef=tableDef('termosFerramentas'),terms=objRows(await listRows(l,termDef,token,sid),termDef.headers),term=terms.find(x=>String(x.TERMO_ID)===String(b.termId));if(!term)throw Object.assign(new Error('Termo de retirada não encontrado.'),{status:409});if(normStatus(term.STATUS)==='FECHADO')throw Object.assign(new Error('Este termo já está fechado.'),{status:409});
        const md=tableDef('movimentosFerramentas'),beforeHistory=objRows(await listRows(l,md,token,sid),md.headers).filter(x=>String(x.TERMO_ID)===String(b.termId)),lastBefore=new Map();beforeHistory.sort((a,z)=>String(a.DATA_HORA).localeCompare(String(z.DATA_HORA))).forEach(x=>lastBefore.set(String(x.FERRAMENTA_ID),x));
        const returnIds=[...new Set((b.movements||[]).map(m=>String(m.FERRAMENTA_ID||'')).filter(Boolean))];if(returnIds.length!==(b.movements||[]).length)throw Object.assign(new Error('Há ferramenta repetida ou sem identificação na devolução.'),{status:400});for(const id of returnIds){const last=lastBefore.get(id);if(!last||normStatus(last.TIPO)!=='SAIDA')throw Object.assign(new Error('A ferramenta '+id+' não está aberta neste termo.'),{status:409,details:{toolId:id}})}
        await upsertObjects(l,'movimentosFerramentas',b.movements,token,sid);const updates=[];for(const m of b.movements){const old=by.get(String(m.FERRAMENTA_ID));if(!old)continue;const n={...old};delete n.__index;n.CONDICAO_ATUAL=m.CONDICAO||n.CONDICAO_ATUAL;const c=normStatus(m.CONDICAO);n.STATUS=c.includes('EXTRAVI')?'EXTRAVIADA':c.includes('AVARI')?'AVARIADA':c.includes('MANUT')?'MANUTENCAO':'DISPONIVEL';n.UPDATED_AT=new Date().toISOString();updates.push(n)}await upsertObjects(l,'ferramentas',updates,token,sid);
        const history=[...beforeHistory,...b.movements],last=new Map();history.sort((a,z)=>String(a.DATA_HORA).localeCompare(String(z.DATA_HORA))).forEach(x=>last.set(String(x.FERRAMENTA_ID),x));const open=[...last.values()].filter(x=>normStatus(x.TIPO)==='SAIDA').length;
        if(open===0){const old=term;if(old){const n={...old};delete n.__index;n.STATUS='FECHADO';n.DATA_HORA_FECHAMENTO=b.receivedAt||new Date().toISOString();n.UPDATED_AT=new Date().toISOString();await upsertObjects(l,'termosFerramentas',[n],token,sid)}}
        await upsertObjects(l,'auditoria',[auditRow('DEVOLUCAO','TERMO_FERRAMENTA',b.termId,null,{movimentos:b.movements},b.user,b.movements[0]?.DEVICE_ID)],token,sid);return {termId:b.termId,count:updates.length,open}
      }));return json(res,200,{ok:true,...result},extra)
    }
    if(url.pathname==='/api/erp/import/commit'&&req.method==='POST'){
      const b=await readJson(req,12*1024*1024);const result=await serialized(()=>withWorkbook(token,async(l,sid)=>{
        if(!b.importacao?.IMPORTACAO_ID||['REJEITADO','BLOQUEADO'].includes(b.importacao.STATUS)||Number(b.importacao.CRITICOS||0)>0)throw Object.assign(new Error('Importação bloqueada: existem erros críticos a corrigir.'),{status:400});const idef=tableDef('importacoes'),imports=objRows(await listRows(l,idef,token,sid),idef.headers);const duplicate=imports.find(x=>String(x.ARQUIVO_HASH)===String(b.importacao.ARQUIVO_HASH)&&normStatus(x.STATUS)!=='REJEITADO');if(duplicate)return {duplicate:true,importId:duplicate.IMPORTACAO_ID,inserted:0,skipped:(b.apontamentos||[]).length};
        const apdef=tableDef('apontamentos'),current=objRows(await listRows(l,apdef,token,sid),apdef.headers),sigs=new Set(current.map(apSignature)),accepted=[],skipped=[];for(const r of b.apontamentos||[]){const s=apSignature(r);if(sigs.has(s)){skipped.push(r);continue}sigs.add(s);accepted.push(r)}
        const fronts=new Map();for(const r of accepted)if(r.FRENTE_ID)fronts.set(r.FRENTE_ID,{FRENTE_ID:r.FRENTE_ID,OBRA_ID:obraId(r.OBRA||''),OBRA:r.OBRA||'',PACOTE_COD:r.PACOTE_COD||'',PACOTE_SERVICO:r.PACOTE_SERVICO||'',ETAPA:r.ETAPA||'',PAVIMENTO:r.PAVIMENTO||'',LOCAL_FRENTE:r.LOCAL_FRENTE||'',STATUS:'ATIVA',CRIADO_EM:new Date().toISOString(),UPDATED_AT:new Date().toISOString()});
        if(fronts.size)await upsertObjects(l,'frentes',[...fronts.values()],token,sid);if(accepted.length)await upsertObjects(l,'apontamentos',accepted,token,sid);
        const occ=[...(b.ocorrencias||[])];for(const r of skipped)occ.push({OCORRENCIA_ID:'OCO-'+crypto.randomUUID().replace(/-/g,'').slice(0,20).toUpperCase(),IMPORTACAO_ID:b.importacao.IMPORTACAO_ID,SEVERIDADE:'INFO',TIPO:'JA_EXISTENTE_NO_ERP',DATA:r.DATA||'',ARQUIVO:b.importacao.ARQUIVO_NOME||'',LINHA:0,CAMPO:'',VALOR:'',DETALHE:`Lançamento de ${r.MATRICULA||''} / ${r.PACOTE_COD||''} já existia e não foi duplicado.`,ACAO:'Nenhuma ação necessária.',UPDATED_AT:new Date().toISOString()});
        const imp={...b.importacao,LINHAS_ACEITAS:accepted.length,ALERTAS:Number(b.importacao.ALERTAS||0)+skipped.length,STATUS:(skipped.length||Number(b.importacao.ALERTAS||0)||Number(b.importacao.CRITICOS||0))?'APROVADO_COM_ALERTAS':'APROVADO',IMPORTADO_POR:b.user||b.importacao.IMPORTADO_POR||'',UPDATED_AT:new Date().toISOString()};await upsertObjects(l,'importacoes',[imp],token,sid);if(occ.length)await upsertObjects(l,'importOcorrencias',occ,token,sid);await upsertObjects(l,'auditoria',[auditRow('IMPORTACAO','APONTAMENTOS',imp.IMPORTACAO_ID,null,{inserted:accepted.length,skipped:skipped.length},b.user,b.deviceId)],token,sid);return {duplicate:false,importId:imp.IMPORTACAO_ID,inserted:accepted.length,skipped:skipped.length}
      }));return json(res,200,{ok:true,...result},extra)
    }
    return false;
  }catch(e){console.error('[ERP]',e);return json(res,e.status||500,{ok:false,error:e.message||String(e),details:e.details||null},extra)}
}

async function handleM365(req,res,url){
  if(url.pathname==='/api/m365/config')return json(res,200,{version:VERSION,authConfigured:authConfigured(),tenant:M365.tenant,clientId:M365.clientId,workbookUrl:M365.workbookUrl,authMode:'server-delegated-cookie'});
  if(url.pathname==='/auth/login'){
    if(!authConfigured())return json(res,503,{ok:false,error:'Microsoft 365 não configurado no servidor. Defina M365_CLIENT_ID, M365_CLIENT_SECRET e SESSION_SECRET no Render.'});const origin=requestOrigin(req),redirectUri=`${origin}/auth/callback`,state=base64url(crypto.randomBytes(24)),returnTo=safeReturnTo(url.searchParams.get('returnTo')||'/'),a=new URL(`https://login.microsoftonline.com/${encodeURIComponent(M365.tenant)}/oauth2/v2.0/authorize`);Object.entries({client_id:M365.clientId,response_type:'code',redirect_uri:redirectUri,response_mode:'query',scope,state,prompt:'select_account'}).forEach(([k,v])=>a.searchParams.set(k,v));return redirect(res,a.toString(),{'Set-Cookie':[cookie(STATE_COOKIE,state,{maxAge:600}),cookie(RETURN_COOKIE,returnTo,{maxAge:600})]})
  }
  if(url.pathname==='/auth/callback'){
    if(!authConfigured())return json(res,503,{ok:false,error:'Microsoft 365 não configurado no servidor.'});const c=cookies(req),expected=c[STATE_COOKIE]||'',got=url.searchParams.get('state')||'',returnTo=safeReturnTo(c[RETURN_COOKIE]||'/');if(!expected||!got||expected!==got)return json(res,400,{ok:false,error:'Resposta de login Microsoft inválida. Tente entrar novamente.'},{'Set-Cookie':[clearCookie(STATE_COOKIE),clearCookie(RETURN_COOKIE)]});const err=url.searchParams.get('error');if(err){const msg=url.searchParams.get('error_description')||err;return redirect(res,`${returnTo}${returnTo.includes('?')?'&':'?'}m365=error&message=${encodeURIComponent(msg)}`,{'Set-Cookie':[clearCookie(STATE_COOKIE),clearCookie(RETURN_COOKIE)]})}const code=url.searchParams.get('code');if(!code)return json(res,400,{ok:false,error:'Código de autorização Microsoft ausente.'});try{const redirectUri=`${requestOrigin(req)}/auth/callback`,t=await tokenRequest({client_id:M365.clientId,client_secret:M365.clientSecret,scope,code,redirect_uri:redirectUri,grant_type:'authorization_code'});if(!t.refresh_token)throw new Error('A Microsoft não devolveu refresh token. Confirme o escopo offline_access.');const session=seal({refreshToken:t.refresh_token,createdAt:Date.now()}),target=`${returnTo}${returnTo.includes('?')?'&':'?'}m365=connected`;return redirect(res,target,{'Set-Cookie':[cookie(SESSION_COOKIE,session,{maxAge:90*24*60*60}),clearCookie(STATE_COOKIE),clearCookie(RETURN_COOKIE)]})}catch(e){return redirect(res,`${returnTo}${returnTo.includes('?')?'&':'?'}m365=error&message=${encodeURIComponent(e.message||String(e))}`,{'Set-Cookie':[clearCookie(STATE_COOKIE),clearCookie(RETURN_COOKIE)]})}
  }
  if(url.pathname==='/api/m365/token'){
    try{const a=await serverAccess(req);return json(res,200,{ok:true,access_token:a.token,expires_in:3300,token_type:'Bearer'},a.setCookie?{'Set-Cookie':a.setCookie}:{})}catch(e){return json(res,e.status||401,{ok:false,reauthRequired:true,error:e.message},e.clearSession?{'Set-Cookie':clearCookie(SESSION_COOKIE)}:{})}
  }
  if(url.pathname==='/auth/logout'){const h={'Set-Cookie':[clearCookie(SESSION_COOKIE),clearCookie(STATE_COOKIE),clearCookie(RETURN_COOKIE)]};if(url.searchParams.get('json')==='1')return json(res,200,{ok:true},h);return redirect(res,'/?m365=logout',h)}
  return false;
}
function safePath(urlPath){const decoded=decodeURIComponent((urlPath||'/').split('?')[0]),rel=decoded==='/'?'index.html':decoded.replace(/^\/+/,''),resolved=path.resolve(root,rel);return resolved.startsWith(root+path.sep)||resolved===root?resolved:null}

const server=http.createServer(async(req,res)=>{
  try{const url=new URL(req.url||'/',requestOrigin(req));
    if(url.pathname==='/healthz')return json(res,200,{ok:true,service:'elevatta-erp',version:VERSION,storage:'offline-first + microsoft365-sharepoint',m365AuthConfigured:authConfigured(),erpSchema:SCHEMA.version});
    if(url.pathname.startsWith('/api/erp/')){const h=await handleErp(req,res,url);if(h!==false)return}
    if(url.pathname.startsWith('/api/m365/')||url.pathname.startsWith('/auth/')){const h=await handleM365(req,res,url);if(h!==false)return}
    if(req.method!=='GET'&&req.method!=='HEAD'){res.writeHead(405,{'Content-Type':'text/plain; charset=utf-8','Allow':'GET, HEAD'});return res.end('Method not allowed')}
    let filePath=safePath(url.pathname);if(!filePath){res.writeHead(400,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Bad request')}let stat;try{stat=await fs.stat(filePath)}catch{}if(stat?.isDirectory())filePath=path.join(filePath,'index.html');let data;try{data=await fs.readFile(filePath)}catch{const ext=path.extname(filePath);if(!ext){filePath=path.join(root,'index.html');data=await fs.readFile(filePath)}else{res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not found')}}const ext=path.extname(filePath).toLowerCase(),base=path.basename(filePath),headers={'Content-Type':mime[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(self), geolocation=(self)','Cross-Origin-Opener-Policy':'same-origin-allow-popups'};headers['Cache-Control']=(['index.html','erp.html','sw.js','manifest.webmanifest','erp-schema.json'].includes(base))?'no-cache, no-store, must-revalidate':'public, max-age=3600';res.writeHead(200,headers);if(req.method==='HEAD')return res.end();res.end(data)
  }catch(err){console.error(err);json(res,err.status||500,{ok:false,error:err.message||'Internal server error'})}
});
server.listen(port,host,()=>{console.log(`Elevatta ERP REV40 em http://${host}:${port}`);console.log('Modo: PWA offline-first + Data Gateway + Microsoft 365 / SharePoint.');console.log(`Microsoft 365 auth: ${authConfigured()?'configurado':'pendente de variáveis no Render'}`)});
